//! Wire-protocol DTOs for the launcher↔Qt-host RPC channel.
//!
//! The Qt host process (C++ binary spawned by `nrr-launcher`) cannot
//! directly link `nrr-ipc-client` (cross-language linkage was rejected
//! in favour of subprocess RPC). Instead the C++ host emits
//! `NRR_IPC_REQUEST:<json>` lines on stdout when QML invokes a
//! `Q_INVOKABLE` bridge method; the launcher reads those lines,
//! dispatches via `nrr-ipc-client::NamedPipeIpcClient`, and writes
//! `NRR_IPC_RESPONSE:<json>` lines to the host's stdin. The host's
//! stdin reader matches the response by `correlation-id`.
//!
//! Why subprocess RPC over FFI:
//! - No cbindgen / linker churn — both processes already exist and
//!   already use stdout/stdin for `NRR_PREFS_JSON:`.
//! - Crash isolation — if the launcher's IPC client dies, the Qt host
//!   keeps painting (degraded but visible).
//! - Simpler debugging — every request is observable in the existing
//!   stdout stream.
//!
//! The trade-offs:
//! - Async-ish wait on QML thread requires a correlation table on both
//!   sides. The host emits a Qt signal when the response arrives,
//!   keyed by correlation-id; QML connects to the signal once and
//!   dispatches per-call promises.
//! - Frame parsing is line-oriented; payload JSON must not contain raw
//!   newlines (we rely on serde_json's default compact output).
//!
//! Operations carried over this channel are the same `IpcOperationName`
//! values from the catalog. The launcher translates the operation slug
//! back to the catalog enum and forwards to the IPC client.

use serde::{Deserialize, Serialize};

/// stdout line prefix the C++ host emits when QML invokes a
/// `Q_INVOKABLE` bridge method that needs to round-trip through the
/// service. The launcher's stdout parser MUST match this exact string
/// (no leading/trailing whitespace allowed) so the protocol stays
/// trivially detectable amidst Qt warning lines and `console.log`
/// output.
pub const RPC_REQUEST_MARKER: &str = "NRR_IPC_REQUEST:";

/// stdin line prefix the launcher emits when it has a response ready.
/// The C++ host's stdin reader matches this exact string.
pub const RPC_RESPONSE_MARKER: &str = "NRR_IPC_RESPONSE:";

/// stdin line prefix for unsolicited push events. Used for
/// `StatusUpdatesSubscribe` flows: after the host issues a subscribe
/// request, the launcher streams subsequent push events on the same
/// stdin channel as separate lines, prefixed with this marker. Each
/// line carries one `LauncherRpcPush` envelope.
pub const RPC_PUSH_MARKER: &str = "NRR_IPC_PUSH:";

/// Launcher → bridge push frame. `subscription_id` matches the
/// `subscription-id` field returned by the original subscribe response;
/// the bridge demultiplexes by it (one host process can have only one
/// subscription today, but the field is included for forward
/// compatibility).
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
pub struct LauncherRpcPush {
    pub subscription_id: String,
    /// `event_id` from the server's `StatusUpdatePushFrame` (monotonic
    /// per subscription). The bridge can use it to detect gaps if it
    /// stores `last_seen_event_id`.
    pub event_id: u64,
    /// The full `StatusUpdateEvent` payload (kebab-case JSON object
    /// with a `type` discriminator). The bridge forwards the JSON
    /// shape unchanged to QML.
    pub event: serde_json::Value,
}

/// Encodes a push frame as the line a launcher writes to host stdin.
pub fn encode_push_line(push: &LauncherRpcPush) -> Result<String, serde_json::Error> {
    let json = serde_json::to_string(push)?;
    Ok(format!("{}{}", RPC_PUSH_MARKER, json))
}

/// Parses a stdin line into a push frame, if it starts with the push
/// marker. Returns `None` for unrelated lines.
pub fn parse_push_line(line: &str) -> Option<Result<LauncherRpcPush, serde_json::Error>> {
    let body = line.strip_prefix(RPC_PUSH_MARKER)?;
    Some(serde_json::from_str(body))
}

/// Bridge → launcher request envelope. The `operation` is one of the
/// stable IPC operation slugs (e.g. `"settings.retention.set"`); the
/// launcher resolves it to `IpcOperationName` via the slug parser.
///
/// `correlation_id` is generated by the C++ host (a monotonic counter
/// is fine; it only needs uniqueness within one host process).
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
pub struct LauncherRpcRequest {
    pub correlation_id: String,
    pub operation: String,
    pub payload: serde_json::Value,
}

/// Launcher → bridge response envelope. Exactly one of `payload` or
/// `error` is populated.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
pub struct LauncherRpcResponse {
    pub correlation_id: String,
    /// `true` when the response carries `payload`; `false` when it
    /// carries `error`. The bridge uses this rather than checking
    /// `error.is_some()` to short-circuit error paths.
    pub ok: bool,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub payload: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub error: Option<LauncherRpcError>,
}

/// Wire-friendly error shape. `code` is a stable kebab-case slug
/// (e.g. `"unknown-operation"`, `"transport-disconnected"`,
/// `"timeout"`); `message` is operator-readable English.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
pub struct LauncherRpcError {
    pub code: String,
    pub message: String,
}

impl LauncherRpcResponse {
    pub fn ok(correlation_id: impl Into<String>, payload: serde_json::Value) -> Self {
        Self {
            correlation_id: correlation_id.into(),
            ok: true,
            payload: Some(payload),
            error: None,
        }
    }

    pub fn err(
        correlation_id: impl Into<String>,
        code: impl Into<String>,
        message: impl Into<String>,
    ) -> Self {
        Self {
            correlation_id: correlation_id.into(),
            ok: false,
            payload: None,
            error: Some(LauncherRpcError {
                code: code.into(),
                message: message.into(),
            }),
        }
    }
}

/// Encodes a request as the line a C++ host would emit on stdout
/// (without the trailing newline — the caller appends `\n`).
pub fn encode_request_line(req: &LauncherRpcRequest) -> Result<String, serde_json::Error> {
    let json = serde_json::to_string(req)?;
    Ok(format!("{}{}", RPC_REQUEST_MARKER, json))
}

/// Encodes a response as the line a launcher would write on the host's
/// stdin (without the trailing newline).
pub fn encode_response_line(resp: &LauncherRpcResponse) -> Result<String, serde_json::Error> {
    let json = serde_json::to_string(resp)?;
    Ok(format!("{}{}", RPC_RESPONSE_MARKER, json))
}

/// Parses a stdout line into a request, if it starts with the request
/// marker. Returns `None` for lines that don't match — the caller
/// continues forwarding those to its own log/stderr.
pub fn parse_request_line(line: &str) -> Option<Result<LauncherRpcRequest, serde_json::Error>> {
    let body = line.strip_prefix(RPC_REQUEST_MARKER)?;
    Some(serde_json::from_str(body))
}

/// Parses a stdin line into a response, if it starts with the response
/// marker. Returns `None` for unrelated lines.
pub fn parse_response_line(line: &str) -> Option<Result<LauncherRpcResponse, serde_json::Error>> {
    let body = line.strip_prefix(RPC_RESPONSE_MARKER)?;
    Some(serde_json::from_str(body))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn request_round_trip_via_line_codec() {
        let req = LauncherRpcRequest {
            correlation_id: "c-1".into(),
            operation: "settings.retention.get".into(),
            payload: serde_json::json!({}),
        };
        let line = encode_request_line(&req).unwrap();
        assert!(line.starts_with(RPC_REQUEST_MARKER));
        let decoded = parse_request_line(&line).unwrap().unwrap();
        assert_eq!(decoded, req);
    }

    #[test]
    fn response_ok_round_trip() {
        let resp = LauncherRpcResponse::ok("c-1", serde_json::json!({"x": 1}));
        let line = encode_response_line(&resp).unwrap();
        let decoded = parse_response_line(&line).unwrap().unwrap();
        assert_eq!(decoded.correlation_id, "c-1");
        assert!(decoded.ok);
        assert_eq!(decoded.payload.unwrap()["x"], 1);
        assert!(decoded.error.is_none());
    }

    #[test]
    fn response_err_round_trip() {
        let resp = LauncherRpcResponse::err("c-2", "transport-disconnected", "service offline");
        let line = encode_response_line(&resp).unwrap();
        let decoded = parse_response_line(&line).unwrap().unwrap();
        assert!(!decoded.ok);
        let err = decoded.error.unwrap();
        assert_eq!(err.code, "transport-disconnected");
        assert_eq!(err.message, "service offline");
        assert!(decoded.payload.is_none());
    }

    #[test]
    fn parser_returns_none_for_unrelated_line() {
        assert!(parse_request_line("Qt warning: foo").is_none());
        assert!(parse_response_line("NRR_PREFS_JSON:{}").is_none());
    }

    #[test]
    fn parser_surfaces_malformed_json() {
        let bad = format!("{RPC_REQUEST_MARKER}{{not valid");
        assert!(parse_request_line(&bad).unwrap().is_err());
    }
}
