//! NetworkManager, resolvconf and the bare file against a fake machine that
//! rewrites `resolv.conf` the way each of them does.

use std::net::Ipv4Addr;
use std::path::Path;
use std::sync::{Arc, Mutex};

use super::*;

const DHCP_SERVER: Ipv4Addr = Ipv4Addr::new(192, 0, 2, 1);
const VPN_SERVER: Ipv4Addr = Ipv4Addr::new(198, 51, 100, 1);

fn scratch(test: &str) -> (tempfile::TempDir, DnsFiles) {
    let dir = tempfile::Builder::new()
        .prefix(&format!("nrr-dns-mech-{test}-"))
        .tempdir()
        .expect("tempdir");
    let root = dir.path();
    std::fs::create_dir_all(root.join("etc")).expect("etc");
    std::fs::create_dir_all(root.join("data")).expect("data");
    std::fs::create_dir_all(root.join("records")).expect("records");
    let files = DnsFiles {
        resolv_conf: root.join("etc").join("resolv.conf"),
        data_dir: root.join("data"),
        nm_conf_dir: root.join("run-nm").join("conf.d"),
        resolvconf_record_dirs: vec![root.join("records")],
        resolved_stub: root.join("run-resolved").join("stub-resolv.conf"),
    };
    (dir, files)
}

fn read(path: &Path) -> String {
    std::fs::read_to_string(path).unwrap_or_default()
}

fn servers_in(path: &Path) -> Vec<Ipv4Addr> {
    resolv_conf::nameservers(&read(path))
}

#[derive(Clone, Copy, PartialEq, Eq)]
enum Resolvconf {
    Absent,
    Openresolv,
    Debian,
}

struct State {
    nm_running: bool,
    /// `false` is `dns=none`: NetworkManager takes a drop-in and never
    /// writes the file.
    nm_writes_file: bool,
    resolvconf: Resolvconf,
    devices: Vec<(String, Vec<Ipv4Addr>, Vec<String>)>,
}

/// A machine without systemd-resolved: NetworkManager and resolvconf rewrite
/// the file as the real ones do.
#[derive(Clone)]
struct FakeMachine {
    files: DnsFiles,
    state: Arc<Mutex<State>>,
    /// The next `nmcli general reload` refuses, then later calls succeed —
    /// simulating the reload that commits a written drop-in failing once.
    fail_next_nm_reload: Arc<Mutex<bool>>,
    /// `resolvconf -a` writes the record (a refused call can still have
    /// written it) but reports failure, as `resolvconf`'s own contract allows.
    fail_resolvconf_add: Arc<Mutex<bool>>,
}

fn reply(success: bool, stdout: &str) -> Result<CommandReply, PlatformError> {
    Ok(CommandReply {
        success,
        stdout: stdout.to_string(),
        stderr: String::new(),
    })
}

impl FakeMachine {
    fn new(files: &DnsFiles) -> Self {
        Self {
            files: files.clone(),
            state: Arc::new(Mutex::new(State {
                nm_running: false,
                nm_writes_file: true,
                resolvconf: Resolvconf::Absent,
                devices: vec![
                    (
                        "nrrtest-wifi".into(),
                        vec![DHCP_SERVER],
                        vec!["lan.example".into()],
                    ),
                    (
                        "nrrtest-vpn".into(),
                        vec![VPN_SERVER],
                        vec!["corp.example".into()],
                    ),
                ],
            })),
            fail_next_nm_reload: Arc::new(Mutex::new(false)),
            fail_resolvconf_add: Arc::new(Mutex::new(false)),
        }
    }

    fn fail_next_nm_reload(&self) {
        *self.fail_next_nm_reload.lock().expect("lock") = true;
    }

    fn fail_resolvconf_add(&self) {
        *self.fail_resolvconf_add.lock().expect("lock") = true;
    }

    fn with_network_manager(self) -> Self {
        self.state.lock().expect("lock").nm_running = true;
        self.nm_write();
        self
    }

    fn with_resolvconf(self, kind: Resolvconf) -> Self {
        self.state.lock().expect("lock").resolvconf = kind;
        let dir = &self.files.resolvconf_record_dirs[0];
        std::fs::write(
            dir.join("nrrtest-wifi.dhclient"),
            format!("nameserver {DHCP_SERVER}\nsearch lan.example\n"),
        )
        .expect("record");
        std::fs::write(
            dir.join("nrrtest-vpn.inet"),
            format!("nameserver {VPN_SERVER}\n"),
        )
        .expect("record");
        self.resolvconf_write();
        self
    }

    /// NetworkManager's `dns=default`: the global drop-in wins over devices.
    fn nm_write(&self) {
        let drop_in = read(&self.files.nm_drop_in());
        let global = drop_in
            .lines()
            .find_map(|l| l.strip_prefix("servers="))
            .map(str::to_string);
        let searches = drop_in
            .lines()
            .find_map(|l| l.strip_prefix("searches="))
            .map(|s| s.replace(',', " "));
        let state = self.state.lock().expect("lock");
        let mut text = String::from("# Generated by NetworkManager\n");
        match (global, searches) {
            (Some(server), searches) => {
                if let Some(searches) = searches {
                    text.push_str(&format!("search {searches}\n"));
                }
                text.push_str(&format!("nameserver {server}\n"));
            }
            (None, _) => {
                let domains: Vec<String> = state.devices.iter().flat_map(|d| d.2.clone()).collect();
                text.push_str(&format!("search {}\n", domains.join(" ")));
                for server in state.devices.iter().flat_map(|d| d.1.clone()) {
                    text.push_str(&format!("nameserver {server}\n"));
                }
            }
        }
        std::fs::write(&self.files.resolv_conf, text).expect("resolv.conf");
    }

    /// resolvconf's merge: `lo.*` first; openresolv honours an exclusive
    /// record, Debian's cuts the list after a loopback server.
    fn resolvconf_write(&self) {
        let dir = &self.files.resolvconf_record_dirs[0];
        let mut records: Vec<(String, String)> = std::fs::read_dir(dir)
            .expect("records")
            .filter_map(Result::ok)
            .map(|e| {
                (
                    e.file_name().to_string_lossy().into_owned(),
                    read(&e.path()),
                )
            })
            .collect();
        records.sort_by_key(|(name, _)| (!name.starts_with("lo."), name.clone()));
        let exclusive = dir.join(".exclusive");
        let exclusive = std::fs::read_to_string(exclusive).ok();
        let mut servers: Vec<Ipv4Addr> = Vec::new();
        for (name, text) in &records {
            if name.starts_with('.') || exclusive.as_ref().is_some_and(|x| x != name) {
                continue;
            }
            servers.extend(resolv_conf::nameservers(text));
        }
        if self.state.lock().expect("lock").resolvconf == Resolvconf::Debian {
            if let Some(cut) = servers.iter().position(|s| s.is_loopback()) {
                servers.truncate(cut + 1);
            }
        }
        let mut text = String::from("# Generated by resolvconf\n");
        for server in servers {
            text.push_str(&format!("nameserver {server}\n"));
        }
        std::fs::write(&self.files.resolv_conf, text).expect("resolv.conf");
    }

    fn resolvconf(
        &self,
        args: &[&str],
        input: Option<&str>,
    ) -> Result<CommandReply, PlatformError> {
        let kind = self.state.lock().expect("lock").resolvconf;
        let dir = self.files.resolvconf_record_dirs[0].clone();
        match (kind, args) {
            (Resolvconf::Absent, _) => Err(PlatformError::Transient {
                operation: "run",
                detail: "resolvconf: not found".into(),
            }),
            (Resolvconf::Openresolv, ["--version"]) => reply(true, "openresolv 3.13.2"),
            (Resolvconf::Debian, ["--version"]) => reply(false, ""),
            (Resolvconf::Openresolv, ["-x", "-a", name]) => {
                std::fs::write(dir.join(name), input.unwrap_or_default()).expect("record");
                std::fs::write(dir.join(".exclusive"), name).expect("exclusive");
                self.resolvconf_write();
                reply(true, "")
            }
            (_, ["-a", name]) => {
                std::fs::write(dir.join(name), input.unwrap_or_default()).expect("record");
                self.resolvconf_write();
                if *self.fail_resolvconf_add.lock().expect("lock") {
                    // Real `resolvconf` can write the record and still report
                    // failure; the redirect must roll back rather than trust
                    // the write it cannot confirm.
                    reply(false, "resolvconf: refused (simulated)")
                } else {
                    reply(true, "")
                }
            }
            (Resolvconf::Openresolv, ["-f", "-d", name]) | (_, ["-d", name]) => {
                let _ = std::fs::remove_file(dir.join(name));
                if read(&dir.join(".exclusive")) == *name {
                    let _ = std::fs::remove_file(dir.join(".exclusive"));
                }
                self.resolvconf_write();
                reply(true, "")
            }
            _ => reply(false, ""),
        }
    }
}

impl DnsCommands for FakeMachine {
    fn run(&self, program: &str, args: &[&str]) -> Result<CommandReply, PlatformError> {
        match (program, args) {
            // No systemd-resolved, no link of ours.
            ("resolvectl", _) => Err(PlatformError::Transient {
                operation: "run",
                detail: "resolvectl: not found".into(),
            }),
            ("ip", ["link", "show", "dev", _]) => reply(false, ""),
            ("nmcli", ["-t", "-f", "RUNNING", "general"]) => {
                let running = self.state.lock().expect("lock").nm_running;
                reply(true, if running { "running\n" } else { "stopped\n" })
            }
            ("nmcli", ["general", "reload"]) => {
                let mut fail_next = self.fail_next_nm_reload.lock().expect("lock");
                if *fail_next {
                    *fail_next = false;
                    return reply(false, "NetworkManager: reload refused (simulated)");
                }
                drop(fail_next);
                if self.state.lock().expect("lock").nm_writes_file {
                    self.nm_write();
                }
                reply(true, "")
            }
            ("nmcli", ["-t", "-f", "GENERAL.DEVICE,IP4.DNS,IP4.DOMAIN", "device", "show"]) => {
                let mut out = String::new();
                for (name, dns, domains) in &self.state.lock().expect("lock").devices {
                    out.push_str(&format!("GENERAL.DEVICE:{name}\n"));
                    for (i, server) in dns.iter().enumerate() {
                        out.push_str(&format!("IP4.DNS[{}]:{server}\n", i + 1));
                    }
                    for (i, domain) in domains.iter().enumerate() {
                        out.push_str(&format!("IP4.DOMAIN[{}]:{domain}\n", i + 1));
                    }
                    out.push('\n');
                }
                reply(true, &out)
            }
            ("resolvconf", args) => self.resolvconf(args, None),
            other => panic!("unexpected command {other:?}"),
        }
    }

    fn run_with_input(
        &self,
        program: &str,
        args: &[&str],
        input: &str,
    ) -> Result<CommandReply, PlatformError> {
        match program {
            "resolvconf" => self.resolvconf(args, Some(input)),
            other => panic!("unexpected command {other} {args:?} with input"),
        }
    }
}

fn plain_file(files: &DnsFiles) -> String {
    let text = format!(
        "# written by hand\nnameserver {DHCP_SERVER}\nnameserver {VPN_SERVER}\nsearch lan.example\noptions edns0\n"
    );
    std::fs::write(&files.resolv_conf, &text).expect("resolv.conf");
    text
}

fn upstreams(servers: &dyn SystemDnsServersPort) -> Vec<Ipv4Addr> {
    servers
        .upstream_candidates_v4()
        .into_iter()
        .map(|c| c.server)
        .collect()
}

// ── choice ───────────────────────────────────────────────────────────────────

#[test]
fn each_machine_gets_the_mechanism_that_writes_its_file() {
    let (_dir, files) = scratch("choice-nm");
    let nm = FakeMachine::new(&files).with_network_manager();
    assert_eq!(
        detect_capture_method(&nm, &files),
        Some(DnsCaptureMethod::NetworkManager)
    );

    let (_dir, files) = scratch("choice-resolvconf");
    let rc = FakeMachine::new(&files).with_resolvconf(Resolvconf::Debian);
    assert_eq!(
        detect_capture_method(&rc, &files),
        Some(DnsCaptureMethod::Resolvconf)
    );

    let (_dir, files) = scratch("choice-file");
    plain_file(&files);
    assert_eq!(
        detect_capture_method(&FakeMachine::new(&files), &files),
        Some(DnsCaptureMethod::ResolvConfFile)
    );

    let (_dir, files) = scratch("choice-none");
    assert_eq!(
        detect_capture_method(&FakeMachine::new(&files), &files),
        None
    );
}

#[test]
fn a_file_networkmanager_once_wrote_is_not_its_while_it_is_stopped() {
    let (_dir, files) = scratch("choice-nm-stopped");
    let machine = FakeMachine::new(&files).with_network_manager();
    machine.state.lock().expect("lock").nm_running = false;
    assert_eq!(
        detect_capture_method(&machine, &files),
        Some(DnsCaptureMethod::ResolvConfFile)
    );
}

/// resolved not answering yet, but the file sends programs to its stub: that
/// is resolved's machine, and taking the file over would forward to ourselves.
#[test]
fn a_file_naming_resolveds_stub_means_resolved_while_it_is_silent() {
    let (_dir, files) = scratch("choice-stub-file");
    std::fs::write(&files.resolv_conf, "nameserver 127.0.0.53\noptions edns0\n").expect("stub");
    assert_eq!(
        detect_capture_method(&FakeMachine::new(&files), &files),
        Some(DnsCaptureMethod::Resolved)
    );
}

#[cfg(unix)]
#[test]
fn a_link_to_resolveds_stub_means_resolved_while_it_is_silent() {
    let (_dir, files) = scratch("choice-stub-link");
    let stub = &files.resolved_stub;
    std::fs::create_dir_all(stub.parent().expect("dir")).expect("dir");
    std::fs::write(stub, "nameserver 127.0.0.53\n").expect("stub");
    std::os::unix::fs::symlink(stub, &files.resolv_conf).expect("link");
    assert_eq!(
        detect_capture_method(&FakeMachine::new(&files), &files),
        Some(DnsCaptureMethod::Resolved)
    );
}

#[test]
fn a_rearm_picks_the_mechanism_the_machine_has_now() {
    let (_dir, files) = scratch("choice-redetect");
    plain_file(&files);
    let machine = FakeMachine::new(&files);
    let selector = DnsCaptureSelector::new(
        DnsCaptureMethod::ResolvConfFile,
        machine.clone(),
        files.clone(),
    );
    assert_eq!(
        selector.redetect(),
        (DnsCaptureMethod::ResolvConfFile, false)
    );

    // NetworkManager came up after the service did.
    let machine = machine.with_network_manager();
    assert_eq!(
        selector.redetect(),
        (DnsCaptureMethod::NetworkManager, true)
    );
    assert_eq!(
        selector.parts(DnsCaptureMethod::NetworkManager).listener,
        LOOPBACK_LISTENER_ADDR
    );

    // A moment with nothing to detect keeps what worked.
    machine.state.lock().expect("lock").nm_running = false;
    std::fs::remove_file(&files.resolv_conf).expect("remove");
    assert_eq!(
        selector.redetect(),
        (DnsCaptureMethod::NetworkManager, false)
    );
}

#[test]
fn every_mechanism_but_resolved_listens_on_loopback() {
    assert_eq!(DnsCaptureMethod::Resolved.listener(), LISTENER_ADDR);
    for method in [
        DnsCaptureMethod::NetworkManager,
        DnsCaptureMethod::Resolvconf,
        DnsCaptureMethod::ResolvConfFile,
    ] {
        assert_eq!(method.listener(), LOOPBACK_LISTENER_ADDR);
    }
}

// ── the bare file ────────────────────────────────────────────────────────────

#[test]
fn the_file_names_only_the_listener_and_keeps_the_search_list() {
    let (_dir, files) = scratch("file-redirect");
    let original = plain_file(&files);
    let servers = ResolvConfFileServers {
        files: files.clone(),
    };
    // Positive control: the reader sees the system's servers before, too.
    assert_eq!(upstreams(&servers), vec![DHCP_SERVER, VPN_SERVER]);

    let redirect = ResolvConfFileRedirect::new(files.clone());
    let handle = redirect
        .redirect_to(LOOPBACK_LISTENER_ADDR)
        .expect("redirects");

    let ours = read(&files.resolv_conf);
    assert_eq!(servers_in(&files.resolv_conf), vec![LOOPBACK_LISTENER_V4]);
    assert!(ours.contains("search lan.example"), "{ours}");
    assert!(ours.contains("options edns0"), "{ours}");
    assert_eq!(
        redirect.verify(&handle).expect("verify"),
        RedirectState::Active
    );
    assert_eq!(upstreams(&servers), vec![DHCP_SERVER, VPN_SERVER]);

    redirect.restore(&handle).expect("restores");
    assert_eq!(read(&files.resolv_conf), original);
    assert!(!files.system_copy().exists());
}

/// dnsmasq or unbound on `127.0.0.1` forwards to whatever the file names —
/// us, once it is redirected. Forwarding to it would loop every query.
#[test]
fn a_local_cache_on_loopback_is_never_an_upstream() {
    let (_dir, files) = scratch("file-loopback-cache");
    std::fs::write(&files.resolv_conf, "nameserver 127.0.0.1\n").expect("resolv.conf");
    let servers = ResolvConfFileServers {
        files: files.clone(),
    };
    assert!(upstreams(&servers).is_empty());

    let redirect = ResolvConfFileRedirect::new(files.clone());
    let handle = redirect
        .redirect_to(LOOPBACK_LISTENER_ADDR)
        .expect("redirects");
    // Read from the copy now, which still names the cache.
    assert!(upstreams(&servers).is_empty());
    redirect.restore(&handle).expect("restores");

    // What the warning is raised on.
    assert_eq!(
        resolv_conf::without_loopback(vec![Ipv4Addr::LOCALHOST, DHCP_SERVER]),
        (vec![DHCP_SERVER], 1)
    );
    // The kernel delivers `0.0.0.0` to this machine, so it loops the same way.
    assert_eq!(
        resolv_conf::without_loopback(resolv_conf::nameservers(
            "nameserver 0.0.0.0\nnameserver 192.0.2.53\n"
        )),
        (vec![Ipv4Addr::new(192, 0, 2, 53)], 1)
    );

    let (_dir, files) = scratch("records-loopback-cache");
    std::fs::write(
        files.resolvconf_record_dirs[0].join("lo.dnsmasq"),
        "nameserver 127.0.0.1\n",
    )
    .expect("record");
    assert!(upstreams(&ResolvconfDnsServers { files }).is_empty());
}

#[cfg(unix)]
#[test]
fn a_symlinked_file_comes_back_as_the_same_symlink() {
    let (_dir, files) = scratch("file-symlink");
    let target = files
        .data_dir
        .parent()
        .expect("root")
        .join("elsewhere.conf");
    std::fs::write(&target, format!("nameserver {DHCP_SERVER}\n")).expect("target");
    std::os::unix::fs::symlink(&target, &files.resolv_conf).expect("link");

    let redirect = ResolvConfFileRedirect::new(files.clone());
    let handle = redirect
        .redirect_to(LOOPBACK_LISTENER_ADDR)
        .expect("redirects");
    assert!(
        std::fs::read_link(&files.resolv_conf).is_err(),
        "ours is a file"
    );
    assert_eq!(
        read(&target),
        format!("nameserver {DHCP_SERVER}\n"),
        "target untouched"
    );

    redirect.restore(&handle).expect("restores");
    assert_eq!(
        std::fs::read_link(&files.resolv_conf).expect("link"),
        target
    );
}

#[test]
fn a_dhcp_client_rewriting_the_file_is_noticed_and_its_version_becomes_the_copy() {
    let (_dir, files) = scratch("file-rewrite");
    plain_file(&files);
    let redirect = ResolvConfFileRedirect::new(files.clone());
    let handle = redirect
        .redirect_to(LOOPBACK_LISTENER_ADDR)
        .expect("redirects");

    let renewed = format!("nameserver {VPN_SERVER}\n");
    std::fs::write(&files.resolv_conf, &renewed).expect("dhcp");
    assert_eq!(
        redirect.inspect(&handle).expect("inspect"),
        RedirectState::Inactive
    );

    redirect
        .redirect_to(LOOPBACK_LISTENER_ADDR)
        .expect("redirects again");
    assert_eq!(
        redirect.inspect(&handle).expect("inspect"),
        RedirectState::Active
    );
    redirect.restore(&handle).expect("restores");
    assert_eq!(read(&files.resolv_conf), renewed);
}

#[test]
fn a_crashed_runs_file_is_put_back_by_the_cleanup() {
    let (_dir, files) = scratch("file-orphan");
    let original = plain_file(&files);
    ResolvConfFileRedirect::new(files.clone())
        .redirect_to(LOOPBACK_LISTENER_ADDR)
        .expect("redirects");
    // No restore: the process died.

    clear_every_redirect(FakeMachine::new(&files), &files).expect("clears");
    assert_eq!(read(&files.resolv_conf), original);
    assert!(!files.system_copy().exists());
}

#[cfg(unix)]
#[test]
fn a_write_failure_rolls_back_to_the_original_file() {
    use std::os::unix::fs::PermissionsExt;

    let (_dir, files) = scratch("file-write-fails");
    let original = plain_file(&files);
    let redirect = ResolvConfFileRedirect::new(files.clone());
    let etc_dir = files.resolv_conf.parent().expect("etc dir").to_path_buf();
    // Denies the temp-file create inside write_atomically for the FINAL
    // redirect write, after the system copy (a different directory) already
    // succeeded — the step this rollback exists for.
    std::fs::set_permissions(&etc_dir, std::fs::Permissions::from_mode(0o555)).expect("chmod");
    let result = redirect.redirect_to(LOOPBACK_LISTENER_ADDR);
    std::fs::set_permissions(&etc_dir, std::fs::Permissions::from_mode(0o755)).expect("chmod back");

    assert!(result.is_err());
    assert_eq!(read(&files.resolv_conf), original);
    assert!(!files.system_copy().exists());
}

#[test]
fn a_listener_resolv_conf_cannot_name_is_refused_before_anything_changes() {
    let (_dir, files) = scratch("file-refused");
    let original = plain_file(&files);
    let redirect = ResolvConfFileRedirect::new(files.clone());
    assert!(redirect.redirect_to(LISTENER_ADDR).is_err());
    let off_port: std::net::SocketAddr = "127.78.82.82:5353".parse().expect("addr");
    assert!(redirect.redirect_to(off_port).is_err());
    assert_eq!(read(&files.resolv_conf), original);
    assert!(!files.system_copy().exists());
}

// ── NetworkManager ───────────────────────────────────────────────────────────

#[test]
fn networkmanager_writes_the_listener_and_the_devices_search_domains() {
    let (_dir, files) = scratch("nm-redirect");
    let machine = FakeMachine::new(&files).with_network_manager();
    // Positive control: before the redirect, the devices' servers are in the file.
    assert_eq!(
        servers_in(&files.resolv_conf),
        vec![DHCP_SERVER, VPN_SERVER]
    );

    let redirect = NetworkManagerDnsRedirect::new(machine.clone(), files.clone());
    let handle = redirect
        .redirect_to(LOOPBACK_LISTENER_ADDR)
        .expect("redirects");
    assert_eq!(servers_in(&files.resolv_conf), vec![LOOPBACK_LISTENER_V4]);
    assert!(read(&files.resolv_conf).contains("search lan.example corp.example"));
    assert_eq!(
        redirect.verify(&handle).expect("verify"),
        RedirectState::Active
    );
    assert_eq!(
        upstreams(&NetworkManagerDnsServers(machine.clone())),
        vec![DHCP_SERVER, VPN_SERVER]
    );

    redirect.restore(&handle).expect("restores");
    assert!(!files.nm_drop_in().exists());
    assert_eq!(
        servers_in(&files.resolv_conf),
        vec![DHCP_SERVER, VPN_SERVER]
    );
    assert_eq!(
        redirect.inspect(&handle).expect("inspect"),
        RedirectState::Inactive
    );
}

/// `dns=none` or a reload that rejected the drop-in leaves the drop-in in
/// place while the file names the devices' servers again.
#[test]
fn networkmanager_no_longer_writing_the_listener_is_noticed() {
    let (_dir, files) = scratch("nm-bypassed");
    let machine = FakeMachine::new(&files).with_network_manager();
    let redirect = NetworkManagerDnsRedirect::new(machine.clone(), files.clone());
    let handle = redirect
        .redirect_to(LOOPBACK_LISTENER_ADDR)
        .expect("redirects");
    // Positive control: as written, the check passes.
    assert_eq!(
        redirect.inspect(&handle).expect("inspect"),
        RedirectState::Active
    );

    std::fs::write(
        &files.resolv_conf,
        format!("# Generated by NetworkManager\nnameserver {DHCP_SERVER}\n"),
    )
    .expect("resolv.conf");
    assert!(files.nm_drop_in().exists());
    assert_eq!(
        redirect.inspect(&handle).expect("inspect"),
        RedirectState::Inactive
    );

    // `dns=dnsmasq`: NetworkManager's own cache in front of us.
    std::fs::write(
        &files.resolv_conf,
        "# Generated by NetworkManager\nnameserver 127.0.0.1\n",
    )
    .expect("resolv.conf");
    assert_eq!(
        redirect.inspect(&handle).expect("inspect"),
        RedirectState::Active
    );
    redirect.restore(&handle).expect("restores");
}

/// `dns=none`: re-writing a drop-in NetworkManager ignores changes nothing,
/// so the redirect moves to the next mechanism once and stays there.
#[test]
fn networkmanager_ignoring_its_drop_in_hands_over_to_the_file() {
    let (_dir, files) = scratch("nm-dns-none");
    let machine = FakeMachine::new(&files).with_network_manager();
    let parts = dns_capture_parts(
        DnsCaptureMethod::NetworkManager,
        machine.clone(),
        files.clone(),
    );
    // Positive control: a NetworkManager that writes the file keeps the job.
    let handle = parts
        .redirect
        .redirect_to(LOOPBACK_LISTENER_ADDR)
        .expect("redirects");
    assert!(files.nm_drop_in().exists());
    assert!(!resolv_conf::is_ours(&read(&files.resolv_conf)));
    parts.redirect.restore(&handle).expect("restores");

    machine.state.lock().expect("lock").nm_writes_file = false;
    let original = read(&files.resolv_conf);
    let handle = parts
        .redirect
        .redirect_to(LOOPBACK_LISTENER_ADDR)
        .expect("hands over");
    assert!(
        !files.nm_drop_in().exists(),
        "the ignored drop-in is taken back"
    );
    assert!(resolv_conf::is_ours(&read(&files.resolv_conf)));
    assert_eq!(servers_in(&files.resolv_conf), vec![LOOPBACK_LISTENER_V4]);
    assert_eq!(
        parts.redirect.inspect(&handle).expect("inspect"),
        RedirectState::Active
    );
    assert_eq!(
        upstreams(parts.servers.as_ref()),
        vec![DHCP_SERVER, VPN_SERVER],
        "the servers follow the file, not the devices"
    );

    // The guard's re-install and a later arm go straight to the file.
    parts
        .redirect
        .redirect_to(LOOPBACK_LISTENER_ADDR)
        .expect("re-installs");
    assert!(!files.nm_drop_in().exists());
    parts.redirect.restore(&handle).expect("restores");
    assert_eq!(read(&files.resolv_conf), original);
    parts
        .redirect
        .redirect_to(LOOPBACK_LISTENER_ADDR)
        .expect("re-arms");
    assert!(!files.nm_drop_in().exists());
    parts.redirect.restore(&handle).expect("restores");
    assert_eq!(read(&files.resolv_conf), original);
}

#[test]
fn a_crashed_runs_networkmanager_drop_in_is_removed_by_the_cleanup() {
    let (_dir, files) = scratch("nm-orphan");
    let machine = FakeMachine::new(&files).with_network_manager();
    NetworkManagerDnsRedirect::new(machine.clone(), files.clone())
        .redirect_to(LOOPBACK_LISTENER_ADDR)
        .expect("redirects");

    clear_every_redirect(machine, &files).expect("clears");
    assert!(!files.nm_drop_in().exists());
    assert_eq!(
        servers_in(&files.resolv_conf),
        vec![DHCP_SERVER, VPN_SERVER]
    );
}

#[test]
fn a_reload_failure_removes_the_drop_in_and_restores_the_file() {
    let (_dir, files) = scratch("nm-reload-fails");
    let machine = FakeMachine::new(&files).with_network_manager();
    machine.fail_next_nm_reload();

    let redirect = NetworkManagerDnsRedirect::new(machine.clone(), files.clone());
    assert!(redirect.redirect_to(LOOPBACK_LISTENER_ADDR).is_err());

    // The refused reload never took the drop-in NetworkManager has not
    // applied would be reapplied by its next reload or restart — the rollback
    // removes it rather than leaving it in place.
    assert!(!files.nm_drop_in().exists());
    assert_eq!(
        servers_in(&files.resolv_conf),
        vec![DHCP_SERVER, VPN_SERVER]
    );
}

#[test]
fn a_device_domain_is_a_scope_with_its_devices_servers() {
    let (_dir, files) = scratch("nm-scopes");
    let machine = FakeMachine::new(&files).with_network_manager();
    let scopes = NetworkManagerDnsScopes(machine).dns_scopes();
    let corp = scopes
        .iter()
        .find(|s| s.suffix == "corp.example")
        .expect("corp scope");
    assert_eq!(corp.servers, vec![VPN_SERVER]);
    assert_eq!(corp.adapter_id, "nrrtest-vpn");
}

#[test]
fn nmcli_terse_output_parses_per_device() {
    let devices = parse_nmcli_devices(
        "GENERAL.DEVICE:eth0\nIP4.DNS[1]:192.0.2.1\nIP4.DNS[2]:192.0.2.2\nIP4.DOMAIN[1]:Lan.Example.\n\nGENERAL.DEVICE:lo\n",
    );
    assert_eq!(devices.len(), 2);
    assert_eq!(
        devices[0].dns,
        vec![Ipv4Addr::new(192, 0, 2, 1), Ipv4Addr::new(192, 0, 2, 2)]
    );
    assert_eq!(devices[0].domains, vec!["lan.example".to_string()]);
    assert!(devices[1].dns.is_empty());
}

// ── resolvconf ───────────────────────────────────────────────────────────────

#[test]
fn openresolv_takes_our_record_exclusively_and_gives_it_back() {
    let (_dir, files) = scratch("openresolv");
    let machine = FakeMachine::new(&files).with_resolvconf(Resolvconf::Openresolv);
    assert_eq!(
        servers_in(&files.resolv_conf),
        vec![VPN_SERVER, DHCP_SERVER]
    );

    let redirect = ResolvconfDnsRedirect::new(machine.clone(), files.clone());
    let handle = redirect
        .redirect_to(LOOPBACK_LISTENER_ADDR)
        .expect("redirects");
    assert_eq!(servers_in(&files.resolv_conf), vec![LOOPBACK_LISTENER_V4]);
    assert_eq!(
        redirect.verify(&handle).expect("verify"),
        RedirectState::Active
    );

    redirect.restore(&handle).expect("restores");
    assert_eq!(
        servers_in(&files.resolv_conf),
        vec![VPN_SERVER, DHCP_SERVER]
    );
}

#[test]
fn debian_resolvconf_lists_our_record_first_and_cuts_the_rest() {
    let (_dir, files) = scratch("debian-resolvconf");
    let machine = FakeMachine::new(&files).with_resolvconf(Resolvconf::Debian);
    let redirect = ResolvconfDnsRedirect::new(machine.clone(), files.clone());
    let handle = redirect
        .redirect_to(LOOPBACK_LISTENER_ADDR)
        .expect("falls back to a plain record");
    assert_eq!(servers_in(&files.resolv_conf), vec![LOOPBACK_LISTENER_V4]);
    assert_eq!(
        redirect.inspect(&handle).expect("inspect"),
        RedirectState::Active
    );

    let servers = ResolvconfDnsServers {
        files: files.clone(),
    };
    assert_eq!(upstreams(&servers), vec![VPN_SERVER, DHCP_SERVER]);
    assert!(servers
        .dns_scopes()
        .iter()
        .any(|s| s.suffix == "lan.example" && s.adapter_id == "nrrtest-wifi"));
}

#[test]
fn a_crashed_runs_resolvconf_record_is_deleted_by_the_cleanup() {
    let (_dir, files) = scratch("resolvconf-orphan");
    let machine = FakeMachine::new(&files).with_resolvconf(Resolvconf::Debian);
    ResolvconfDnsRedirect::new(machine.clone(), files.clone())
        .redirect_to(LOOPBACK_LISTENER_ADDR)
        .expect("redirects");
    assert_eq!(servers_in(&files.resolv_conf), vec![LOOPBACK_LISTENER_V4]);

    clear_every_redirect(machine, &files).expect("clears");
    assert_eq!(
        servers_in(&files.resolv_conf),
        vec![VPN_SERVER, DHCP_SERVER]
    );
    assert!(!files.resolvconf_record_dirs[0]
        .join(resolvconf_record())
        .exists());
}

#[test]
fn an_add_failure_leaves_no_record_behind() {
    let (_dir, files) = scratch("resolvconf-add-fails");
    let machine = FakeMachine::new(&files).with_resolvconf(Resolvconf::Debian);
    machine.fail_resolvconf_add();

    let redirect = ResolvconfDnsRedirect::new(machine.clone(), files.clone());
    // A refused call can still have written the record before failing; the
    // rollback must delete it rather than trust the write it cannot confirm.
    assert!(redirect.redirect_to(LOOPBACK_LISTENER_ADDR).is_err());
    assert!(!files.resolvconf_record_dirs[0]
        .join(resolvconf_record())
        .exists());
    assert_eq!(
        servers_in(&files.resolv_conf),
        vec![VPN_SERVER, DHCP_SERVER]
    );
}

#[test]
fn the_cleanup_on_a_clean_machine_touches_nothing() {
    let (_dir, files) = scratch("clean");
    let original = plain_file(&files);
    clear_every_redirect(FakeMachine::new(&files), &files).expect("clears");
    assert_eq!(read(&files.resolv_conf), original);
}
