//! NetworkManager, resolvconf and the bare file against a fake machine that
//! rewrites `resolv.conf` the way each of them does.

use std::net::Ipv4Addr;
use std::path::Path;
use std::sync::{Arc, Mutex};

use super::*;

const DHCP_SERVER: Ipv4Addr = Ipv4Addr::new(192, 0, 2, 1);
const VPN_SERVER: Ipv4Addr = Ipv4Addr::new(198, 51, 100, 1);

fn scratch(test: &str) -> DnsFiles {
    let root = std::env::temp_dir().join(format!("nrr-dns-mech-{test}-{}", std::process::id()));
    let _ = std::fs::remove_dir_all(&root);
    std::fs::create_dir_all(root.join("etc")).expect("etc");
    std::fs::create_dir_all(root.join("data")).expect("data");
    std::fs::create_dir_all(root.join("records")).expect("records");
    DnsFiles {
        resolv_conf: root.join("etc").join("resolv.conf"),
        data_dir: root.join("data"),
        nm_conf_dir: root.join("run-nm").join("conf.d"),
        resolvconf_record_dirs: vec![root.join("records")],
        resolved_stub: root.join("run-resolved").join("stub-resolv.conf"),
    }
}

fn read(path: &Path) -> String {
    std::fs::read_to_string(path).unwrap_or_default()
}

fn servers_in(path: &Path) -> Vec<Ipv4Addr> {
    resolv_conf::nameservers(&read(path))
}

#[derive(Clone, Copy, PartialEq, Eq)]
enum Resolvconf {
    Absent,
    Openresolv,
    Debian,
}

struct State {
    nm_running: bool,
    resolvconf: Resolvconf,
    devices: Vec<(String, Vec<Ipv4Addr>, Vec<String>)>,
}

/// A machine without systemd-resolved: NetworkManager and resolvconf rewrite
/// the file as the real ones do.
#[derive(Clone)]
struct FakeMachine {
    files: DnsFiles,
    state: Arc<Mutex<State>>,
}

fn reply(success: bool, stdout: &str) -> Result<CommandReply, PlatformError> {
    Ok(CommandReply {
        success,
        stdout: stdout.to_string(),
        stderr: String::new(),
    })
}

impl FakeMachine {
    fn new(files: &DnsFiles) -> Self {
        Self {
            files: files.clone(),
            state: Arc::new(Mutex::new(State {
                nm_running: false,
                resolvconf: Resolvconf::Absent,
                devices: vec![
                    (
                        "nrrtest-wifi".into(),
                        vec![DHCP_SERVER],
                        vec!["lan.example".into()],
                    ),
                    (
                        "nrrtest-vpn".into(),
                        vec![VPN_SERVER],
                        vec!["corp.example".into()],
                    ),
                ],
            })),
        }
    }

    fn with_network_manager(self) -> Self {
        self.state.lock().expect("lock").nm_running = true;
        self.nm_write();
        self
    }

    fn with_resolvconf(self, kind: Resolvconf) -> Self {
        self.state.lock().expect("lock").resolvconf = kind;
        let dir = &self.files.resolvconf_record_dirs[0];
        std::fs::write(
            dir.join("nrrtest-wifi.dhclient"),
            format!("nameserver {DHCP_SERVER}\nsearch lan.example\n"),
        )
        .expect("record");
        std::fs::write(
            dir.join("nrrtest-vpn.inet"),
            format!("nameserver {VPN_SERVER}\n"),
        )
        .expect("record");
        self.resolvconf_write();
        self
    }

    /// NetworkManager's `dns=default`: the global drop-in wins over devices.
    fn nm_write(&self) {
        let drop_in = read(&self.files.nm_drop_in());
        let global = drop_in
            .lines()
            .find_map(|l| l.strip_prefix("servers="))
            .map(str::to_string);
        let searches = drop_in
            .lines()
            .find_map(|l| l.strip_prefix("searches="))
            .map(|s| s.replace(',', " "));
        let state = self.state.lock().expect("lock");
        let mut text = String::from("# Generated by NetworkManager\n");
        match (global, searches) {
            (Some(server), searches) => {
                if let Some(searches) = searches {
                    text.push_str(&format!("search {searches}\n"));
                }
                text.push_str(&format!("nameserver {server}\n"));
            }
            (None, _) => {
                let domains: Vec<String> = state.devices.iter().flat_map(|d| d.2.clone()).collect();
                text.push_str(&format!("search {}\n", domains.join(" ")));
                for server in state.devices.iter().flat_map(|d| d.1.clone()) {
                    text.push_str(&format!("nameserver {server}\n"));
                }
            }
        }
        std::fs::write(&self.files.resolv_conf, text).expect("resolv.conf");
    }

    /// resolvconf's merge: `lo.*` first; openresolv honours an exclusive
    /// record, Debian's cuts the list after a loopback server.
    fn resolvconf_write(&self) {
        let dir = &self.files.resolvconf_record_dirs[0];
        let mut records: Vec<(String, String)> = std::fs::read_dir(dir)
            .expect("records")
            .filter_map(Result::ok)
            .map(|e| {
                (
                    e.file_name().to_string_lossy().into_owned(),
                    read(&e.path()),
                )
            })
            .collect();
        records.sort_by_key(|(name, _)| (!name.starts_with("lo."), name.clone()));
        let exclusive = dir.join(".exclusive");
        let exclusive = std::fs::read_to_string(exclusive).ok();
        let mut servers: Vec<Ipv4Addr> = Vec::new();
        for (name, text) in &records {
            if name.starts_with('.') || exclusive.as_ref().is_some_and(|x| x != name) {
                continue;
            }
            servers.extend(resolv_conf::nameservers(text));
        }
        if self.state.lock().expect("lock").resolvconf == Resolvconf::Debian {
            if let Some(cut) = servers.iter().position(|s| s.is_loopback()) {
                servers.truncate(cut + 1);
            }
        }
        let mut text = String::from("# Generated by resolvconf\n");
        for server in servers {
            text.push_str(&format!("nameserver {server}\n"));
        }
        std::fs::write(&self.files.resolv_conf, text).expect("resolv.conf");
    }

    fn resolvconf(
        &self,
        args: &[&str],
        input: Option<&str>,
    ) -> Result<CommandReply, PlatformError> {
        let kind = self.state.lock().expect("lock").resolvconf;
        let dir = self.files.resolvconf_record_dirs[0].clone();
        match (kind, args) {
            (Resolvconf::Absent, _) => Err(PlatformError::Transient {
                operation: "run",
                detail: "resolvconf: not found".into(),
            }),
            (Resolvconf::Openresolv, ["--version"]) => reply(true, "openresolv 3.13.2"),
            (Resolvconf::Debian, ["--version"]) => reply(false, ""),
            (Resolvconf::Openresolv, ["-x", "-a", name]) => {
                std::fs::write(dir.join(name), input.unwrap_or_default()).expect("record");
                std::fs::write(dir.join(".exclusive"), name).expect("exclusive");
                self.resolvconf_write();
                reply(true, "")
            }
            (_, ["-a", name]) => {
                std::fs::write(dir.join(name), input.unwrap_or_default()).expect("record");
                self.resolvconf_write();
                reply(true, "")
            }
            (Resolvconf::Openresolv, ["-f", "-d", name]) | (_, ["-d", name]) => {
                let _ = std::fs::remove_file(dir.join(name));
                if read(&dir.join(".exclusive")) == *name {
                    let _ = std::fs::remove_file(dir.join(".exclusive"));
                }
                self.resolvconf_write();
                reply(true, "")
            }
            _ => reply(false, ""),
        }
    }
}

impl DnsCommands for FakeMachine {
    fn run(&self, program: &str, args: &[&str]) -> Result<CommandReply, PlatformError> {
        match (program, args) {
            // No systemd-resolved, no link of ours.
            ("resolvectl", _) => Err(PlatformError::Transient {
                operation: "run",
                detail: "resolvectl: not found".into(),
            }),
            ("ip", ["link", "show", "dev", _]) => reply(false, ""),
            ("nmcli", ["-t", "-f", "RUNNING", "general"]) => {
                let running = self.state.lock().expect("lock").nm_running;
                reply(true, if running { "running\n" } else { "stopped\n" })
            }
            ("nmcli", ["general", "reload"]) => {
                self.nm_write();
                reply(true, "")
            }
            ("nmcli", ["-t", "-f", "GENERAL.DEVICE,IP4.DNS,IP4.DOMAIN", "device", "show"]) => {
                let mut out = String::new();
                for (name, dns, domains) in &self.state.lock().expect("lock").devices {
                    out.push_str(&format!("GENERAL.DEVICE:{name}\n"));
                    for (i, server) in dns.iter().enumerate() {
                        out.push_str(&format!("IP4.DNS[{}]:{server}\n", i + 1));
                    }
                    for (i, domain) in domains.iter().enumerate() {
                        out.push_str(&format!("IP4.DOMAIN[{}]:{domain}\n", i + 1));
                    }
                    out.push('\n');
                }
                reply(true, &out)
            }
            ("resolvconf", args) => self.resolvconf(args, None),
            other => panic!("unexpected command {other:?}"),
        }
    }

    fn run_with_input(
        &self,
        program: &str,
        args: &[&str],
        input: &str,
    ) -> Result<CommandReply, PlatformError> {
        match program {
            "resolvconf" => self.resolvconf(args, Some(input)),
            other => panic!("unexpected command {other} {args:?} with input"),
        }
    }
}

fn plain_file(files: &DnsFiles) -> String {
    let text = format!(
        "# written by hand\nnameserver {DHCP_SERVER}\nnameserver {VPN_SERVER}\nsearch lan.example\noptions edns0\n"
    );
    std::fs::write(&files.resolv_conf, &text).expect("resolv.conf");
    text
}

fn upstreams(servers: &dyn SystemDnsServersPort) -> Vec<Ipv4Addr> {
    servers
        .upstream_candidates_v4()
        .into_iter()
        .map(|c| c.server)
        .collect()
}

// ── choice ───────────────────────────────────────────────────────────────────

#[test]
fn each_machine_gets_the_mechanism_that_writes_its_file() {
    let files = scratch("choice-nm");
    let nm = FakeMachine::new(&files).with_network_manager();
    assert_eq!(
        detect_capture_method(&nm, &files),
        Some(DnsCaptureMethod::NetworkManager)
    );

    let files = scratch("choice-resolvconf");
    let rc = FakeMachine::new(&files).with_resolvconf(Resolvconf::Debian);
    assert_eq!(
        detect_capture_method(&rc, &files),
        Some(DnsCaptureMethod::Resolvconf)
    );

    let files = scratch("choice-file");
    plain_file(&files);
    assert_eq!(
        detect_capture_method(&FakeMachine::new(&files), &files),
        Some(DnsCaptureMethod::ResolvConfFile)
    );

    let files = scratch("choice-none");
    assert_eq!(
        detect_capture_method(&FakeMachine::new(&files), &files),
        None
    );
}

#[test]
fn a_file_networkmanager_once_wrote_is_not_its_while_it_is_stopped() {
    let files = scratch("choice-nm-stopped");
    let machine = FakeMachine::new(&files).with_network_manager();
    machine.state.lock().expect("lock").nm_running = false;
    assert_eq!(
        detect_capture_method(&machine, &files),
        Some(DnsCaptureMethod::ResolvConfFile)
    );
}

#[test]
fn every_mechanism_but_resolved_listens_on_loopback() {
    assert_eq!(DnsCaptureMethod::Resolved.listener(), LISTENER_ADDR);
    for method in [
        DnsCaptureMethod::NetworkManager,
        DnsCaptureMethod::Resolvconf,
        DnsCaptureMethod::ResolvConfFile,
    ] {
        assert_eq!(method.listener(), LOOPBACK_LISTENER_ADDR);
    }
}

// ── the bare file ────────────────────────────────────────────────────────────

#[test]
fn the_file_names_only_the_listener_and_keeps_the_search_list() {
    let files = scratch("file-redirect");
    let original = plain_file(&files);
    let servers = ResolvConfFileServers {
        files: files.clone(),
    };
    // Positive control: the reader sees the system's servers before, too.
    assert_eq!(upstreams(&servers), vec![DHCP_SERVER, VPN_SERVER]);

    let redirect = ResolvConfFileRedirect::new(files.clone());
    let handle = redirect
        .redirect_to(LOOPBACK_LISTENER_ADDR)
        .expect("redirects");

    let ours = read(&files.resolv_conf);
    assert_eq!(servers_in(&files.resolv_conf), vec![LOOPBACK_LISTENER_V4]);
    assert!(ours.contains("search lan.example"), "{ours}");
    assert!(ours.contains("options edns0"), "{ours}");
    assert_eq!(
        redirect.verify(&handle).expect("verify"),
        RedirectState::Active
    );
    assert_eq!(upstreams(&servers), vec![DHCP_SERVER, VPN_SERVER]);

    redirect.restore(&handle).expect("restores");
    assert_eq!(read(&files.resolv_conf), original);
    assert!(!files.system_copy().exists());
}

#[cfg(unix)]
#[test]
fn a_symlinked_file_comes_back_as_the_same_symlink() {
    let files = scratch("file-symlink");
    let target = files
        .data_dir
        .parent()
        .expect("root")
        .join("elsewhere.conf");
    std::fs::write(&target, format!("nameserver {DHCP_SERVER}\n")).expect("target");
    std::os::unix::fs::symlink(&target, &files.resolv_conf).expect("link");

    let redirect = ResolvConfFileRedirect::new(files.clone());
    let handle = redirect
        .redirect_to(LOOPBACK_LISTENER_ADDR)
        .expect("redirects");
    assert!(
        std::fs::read_link(&files.resolv_conf).is_err(),
        "ours is a file"
    );
    assert_eq!(
        read(&target),
        format!("nameserver {DHCP_SERVER}\n"),
        "target untouched"
    );

    redirect.restore(&handle).expect("restores");
    assert_eq!(
        std::fs::read_link(&files.resolv_conf).expect("link"),
        target
    );
}

#[test]
fn a_dhcp_client_rewriting_the_file_is_noticed_and_its_version_becomes_the_copy() {
    let files = scratch("file-rewrite");
    plain_file(&files);
    let redirect = ResolvConfFileRedirect::new(files.clone());
    let handle = redirect
        .redirect_to(LOOPBACK_LISTENER_ADDR)
        .expect("redirects");

    let renewed = format!("nameserver {VPN_SERVER}\n");
    std::fs::write(&files.resolv_conf, &renewed).expect("dhcp");
    assert_eq!(
        redirect.inspect(&handle).expect("inspect"),
        RedirectState::Inactive
    );

    redirect
        .redirect_to(LOOPBACK_LISTENER_ADDR)
        .expect("redirects again");
    assert_eq!(
        redirect.inspect(&handle).expect("inspect"),
        RedirectState::Active
    );
    redirect.restore(&handle).expect("restores");
    assert_eq!(read(&files.resolv_conf), renewed);
}

#[test]
fn a_crashed_runs_file_is_put_back_by_the_cleanup() {
    let files = scratch("file-orphan");
    let original = plain_file(&files);
    ResolvConfFileRedirect::new(files.clone())
        .redirect_to(LOOPBACK_LISTENER_ADDR)
        .expect("redirects");
    // No restore: the process died.

    clear_every_redirect(FakeMachine::new(&files), &files).expect("clears");
    assert_eq!(read(&files.resolv_conf), original);
    assert!(!files.system_copy().exists());
}

#[test]
fn a_listener_resolv_conf_cannot_name_is_refused_before_anything_changes() {
    let files = scratch("file-refused");
    let original = plain_file(&files);
    let redirect = ResolvConfFileRedirect::new(files.clone());
    assert!(redirect.redirect_to(LISTENER_ADDR).is_err());
    let off_port: std::net::SocketAddr = "127.78.82.82:5353".parse().expect("addr");
    assert!(redirect.redirect_to(off_port).is_err());
    assert_eq!(read(&files.resolv_conf), original);
    assert!(!files.system_copy().exists());
}

// ── NetworkManager ───────────────────────────────────────────────────────────

#[test]
fn networkmanager_writes_the_listener_and_the_devices_search_domains() {
    let files = scratch("nm-redirect");
    let machine = FakeMachine::new(&files).with_network_manager();
    // Positive control: before the redirect, the devices' servers are in the file.
    assert_eq!(
        servers_in(&files.resolv_conf),
        vec![DHCP_SERVER, VPN_SERVER]
    );

    let redirect = NetworkManagerDnsRedirect::new(machine.clone(), files.clone());
    let handle = redirect
        .redirect_to(LOOPBACK_LISTENER_ADDR)
        .expect("redirects");
    assert_eq!(servers_in(&files.resolv_conf), vec![LOOPBACK_LISTENER_V4]);
    assert!(read(&files.resolv_conf).contains("search lan.example corp.example"));
    assert_eq!(
        redirect.verify(&handle).expect("verify"),
        RedirectState::Active
    );
    assert_eq!(
        upstreams(&NetworkManagerDnsServers(machine.clone())),
        vec![DHCP_SERVER, VPN_SERVER]
    );

    redirect.restore(&handle).expect("restores");
    assert!(!files.nm_drop_in().exists());
    assert_eq!(
        servers_in(&files.resolv_conf),
        vec![DHCP_SERVER, VPN_SERVER]
    );
    assert_eq!(
        redirect.inspect(&handle).expect("inspect"),
        RedirectState::Inactive
    );
}

#[test]
fn a_crashed_runs_networkmanager_drop_in_is_removed_by_the_cleanup() {
    let files = scratch("nm-orphan");
    let machine = FakeMachine::new(&files).with_network_manager();
    NetworkManagerDnsRedirect::new(machine.clone(), files.clone())
        .redirect_to(LOOPBACK_LISTENER_ADDR)
        .expect("redirects");

    clear_every_redirect(machine, &files).expect("clears");
    assert!(!files.nm_drop_in().exists());
    assert_eq!(
        servers_in(&files.resolv_conf),
        vec![DHCP_SERVER, VPN_SERVER]
    );
}

#[test]
fn a_device_domain_is_a_scope_with_its_devices_servers() {
    let files = scratch("nm-scopes");
    let machine = FakeMachine::new(&files).with_network_manager();
    let scopes = NetworkManagerDnsScopes(machine).dns_scopes();
    let corp = scopes
        .iter()
        .find(|s| s.suffix == "corp.example")
        .expect("corp scope");
    assert_eq!(corp.servers, vec![VPN_SERVER]);
    assert_eq!(corp.adapter_id, "nrrtest-vpn");
}

#[test]
fn nmcli_terse_output_parses_per_device() {
    let devices = parse_nmcli_devices(
        "GENERAL.DEVICE:eth0\nIP4.DNS[1]:192.0.2.1\nIP4.DNS[2]:192.0.2.2\nIP4.DOMAIN[1]:Lan.Example.\n\nGENERAL.DEVICE:lo\n",
    );
    assert_eq!(devices.len(), 2);
    assert_eq!(
        devices[0].dns,
        vec![Ipv4Addr::new(192, 0, 2, 1), Ipv4Addr::new(192, 0, 2, 2)]
    );
    assert_eq!(devices[0].domains, vec!["lan.example".to_string()]);
    assert!(devices[1].dns.is_empty());
}

// ── resolvconf ───────────────────────────────────────────────────────────────

#[test]
fn openresolv_takes_our_record_exclusively_and_gives_it_back() {
    let files = scratch("openresolv");
    let machine = FakeMachine::new(&files).with_resolvconf(Resolvconf::Openresolv);
    assert_eq!(
        servers_in(&files.resolv_conf),
        vec![VPN_SERVER, DHCP_SERVER]
    );

    let redirect = ResolvconfDnsRedirect::new(machine.clone(), files.clone());
    let handle = redirect
        .redirect_to(LOOPBACK_LISTENER_ADDR)
        .expect("redirects");
    assert_eq!(servers_in(&files.resolv_conf), vec![LOOPBACK_LISTENER_V4]);
    assert_eq!(
        redirect.verify(&handle).expect("verify"),
        RedirectState::Active
    );

    redirect.restore(&handle).expect("restores");
    assert_eq!(
        servers_in(&files.resolv_conf),
        vec![VPN_SERVER, DHCP_SERVER]
    );
}

#[test]
fn debian_resolvconf_lists_our_record_first_and_cuts_the_rest() {
    let files = scratch("debian-resolvconf");
    let machine = FakeMachine::new(&files).with_resolvconf(Resolvconf::Debian);
    let redirect = ResolvconfDnsRedirect::new(machine.clone(), files.clone());
    let handle = redirect
        .redirect_to(LOOPBACK_LISTENER_ADDR)
        .expect("falls back to a plain record");
    assert_eq!(servers_in(&files.resolv_conf), vec![LOOPBACK_LISTENER_V4]);
    assert_eq!(
        redirect.inspect(&handle).expect("inspect"),
        RedirectState::Active
    );

    let servers = ResolvconfDnsServers {
        files: files.clone(),
    };
    assert_eq!(upstreams(&servers), vec![VPN_SERVER, DHCP_SERVER]);
    assert!(servers
        .dns_scopes()
        .iter()
        .any(|s| s.suffix == "lan.example" && s.adapter_id == "nrrtest-wifi"));
}

#[test]
fn a_crashed_runs_resolvconf_record_is_deleted_by_the_cleanup() {
    let files = scratch("resolvconf-orphan");
    let machine = FakeMachine::new(&files).with_resolvconf(Resolvconf::Debian);
    ResolvconfDnsRedirect::new(machine.clone(), files.clone())
        .redirect_to(LOOPBACK_LISTENER_ADDR)
        .expect("redirects");
    assert_eq!(servers_in(&files.resolv_conf), vec![LOOPBACK_LISTENER_V4]);

    clear_every_redirect(machine, &files).expect("clears");
    assert_eq!(
        servers_in(&files.resolv_conf),
        vec![VPN_SERVER, DHCP_SERVER]
    );
    assert!(!files.resolvconf_record_dirs[0]
        .join(resolvconf_record())
        .exists());
}

#[test]
fn the_cleanup_on_a_clean_machine_touches_nothing() {
    let files = scratch("clean");
    let original = plain_file(&files);
    clear_every_redirect(FakeMachine::new(&files), &files).expect("clears");
    assert_eq!(read(&files.resolv_conf), original);
}
