//! System DNS redirect through NetworkManager, where NetworkManager writes
//! `/etc/resolv.conf` and systemd-resolved does not stand in between (the
//! RHEL family, RED OS, Astra).
//!
//! A global-DNS drop-in names the listener as the server for every name;
//! NetworkManager rewrites the file itself and keeps it that way across
//! reconnects. The drop-in lives under `/run`, so a reboot forgets it even if
//! nothing else does.

use std::net::{Ipv4Addr, SocketAddr};

use nrr_platform_api::dns::{SystemDnsServersPort, UpstreamDnsCandidate};
use nrr_platform_api::dns_redirect::{RedirectHandle, RedirectState, SystemDnsRedirectPort};
use nrr_platform_api::dns_scope::{InterfaceDnsScope, InterfaceDnsScopePort};
use nrr_platform_api::error::PlatformError;

use super::resolv_conf::{forwardable, nameservers, write_atomically, OURS_MARKER};
use super::{DnsCommands, DnsFiles};

/// Does NetworkManager write this `resolv.conf`?
pub fn network_manager_writes(resolv_conf: &str) -> bool {
    resolv_conf
        .lines()
        .take_while(|l| l.starts_with('#'))
        .any(|l| l.contains("Generated by NetworkManager"))
}

/// Is NetworkManager running and writing the machine's `resolv.conf`?
pub fn network_manager_redirect_available(commands: &dyn DnsCommands, files: &DnsFiles) -> bool {
    let writes =
        std::fs::read_to_string(&files.resolv_conf).is_ok_and(|text| network_manager_writes(&text));
    writes
        && commands
            .run("nmcli", &["-t", "-f", "RUNNING", "general"])
            .is_ok_and(|r| r.success && r.stdout.trim() == "running")
}

/// One device as `nmcli device show` describes it.
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct NmDevice {
    pub name: String,
    pub dns: Vec<Ipv4Addr>,
    pub domains: Vec<String>,
}

/// Parse `nmcli -t -f GENERAL.DEVICE,IP4.DNS,IP4.DOMAIN device show`.
pub fn parse_nmcli_devices(text: &str) -> Vec<NmDevice> {
    let mut out: Vec<NmDevice> = Vec::new();
    for line in text.lines() {
        let Some((key, value)) = line.split_once(':') else {
            continue;
        };
        let value = value.trim();
        if key == "GENERAL.DEVICE" {
            out.push(NmDevice {
                name: value.to_string(),
                ..NmDevice::default()
            });
            continue;
        }
        let Some(device) = out.last_mut() else {
            continue;
        };
        if key.starts_with("IP4.DNS") {
            if let Ok(ip) = value.parse() {
                device.dns.push(ip);
            }
        } else if key.starts_with("IP4.DOMAIN") {
            let suffix = value.trim_matches('.').to_ascii_lowercase();
            if !suffix.is_empty() {
                device.domains.push(suffix);
            }
        }
    }
    out
}

fn devices(commands: &dyn DnsCommands) -> Vec<NmDevice> {
    commands
        .run(
            "nmcli",
            &[
                "-t",
                "-f",
                "GENERAL.DEVICE,IP4.DNS,IP4.DOMAIN",
                "device",
                "show",
            ],
        )
        .ok()
        .filter(|r| r.success)
        .map(|r| parse_nmcli_devices(&r.stdout))
        .unwrap_or_default()
}

/// The drop-in text: the listener for every name, and the devices' search
/// domains kept — the global setting replaces theirs.
fn render(listener: Ipv4Addr, searches: &[String]) -> String {
    let mut text = format!("{OURS_MARKER}\n");
    if !searches.is_empty() {
        text.push_str(&format!("[global-dns]\nsearches={}\n", searches.join(",")));
    }
    text.push_str(&format!("[global-dns-domain-*]\nservers={listener}\n"));
    text
}

fn reload(commands: &dyn DnsCommands) -> Result<(), PlatformError> {
    let reply = commands.run("nmcli", &["general", "reload"])?;
    if reply.success {
        Ok(())
    } else {
        Err(PlatformError::Transient {
            operation: "reload NetworkManager's DNS configuration",
            detail: reply.stderr.trim().to_string(),
        })
    }
}

/// The NetworkManager redirect.
pub struct NetworkManagerDnsRedirect<C: DnsCommands> {
    commands: C,
    files: DnsFiles,
}

impl<C: DnsCommands> NetworkManagerDnsRedirect<C> {
    pub fn new(commands: C, files: DnsFiles) -> Self {
        Self { commands, files }
    }

    fn drop_in_is_ours(&self) -> bool {
        std::fs::read_to_string(self.files.nm_drop_in())
            .is_ok_and(|text| super::resolv_conf::is_ours(&text))
    }
}

impl<C: DnsCommands> SystemDnsRedirectPort for NetworkManagerDnsRedirect<C> {
    fn redirect_to(&self, listener: SocketAddr) -> Result<RedirectHandle, PlatformError> {
        let listener_v4 = super::loopback_listener_v4(listener)?;
        let mut searches: Vec<String> = Vec::new();
        for domain in devices(&self.commands).into_iter().flat_map(|d| d.domains) {
            if !searches.contains(&domain) {
                searches.push(domain);
            }
        }
        std::fs::create_dir_all(&self.files.nm_conf_dir).map_err(|e| PlatformError::Transient {
            operation: "create NetworkManager's runtime configuration directory",
            detail: e.to_string(),
        })?;
        write_atomically(&self.files.nm_drop_in(), &render(listener_v4, &searches))?;
        // A drop-in NetworkManager has not taken would be taken by its next
        // reload or restart, pointing every name at a listener long gone.
        if let Err(error) = reload(&self.commands) {
            let _ = clear_network_manager_redirect(&self.commands, &self.files);
            return Err(error);
        }
        Ok(RedirectHandle {
            marker: "networkmanager:global-dns".to_string(),
            listener,
        })
    }

    fn restore(&self, _handle: &RedirectHandle) -> Result<(), PlatformError> {
        clear_network_manager_redirect(&self.commands, &self.files)
    }

    fn verify(&self, handle: &RedirectHandle) -> Result<RedirectState, PlatformError> {
        let listener = super::loopback_listener_v4(handle.listener)?;
        let written = std::fs::read_to_string(&self.files.resolv_conf)
            .is_ok_and(|text| nameservers(&text) == [listener]);
        Ok(if self.drop_in_is_ours() && written {
            RedirectState::Active
        } else {
            RedirectState::Inactive
        })
    }

    fn inspect(&self, _handle: &RedirectHandle) -> Result<RedirectState, PlatformError> {
        // NetworkManager keeps writing what the drop-in says; the drop-in is
        // what can go missing. The file may name a local cache NetworkManager
        // runs in front of us, so it is not the test here.
        Ok(if self.drop_in_is_ours() {
            RedirectState::Active
        } else {
            RedirectState::Inactive
        })
    }
}

/// Remove our drop-in and let NetworkManager rewrite the file. Idempotent;
/// also the orphan cleanup after a crash.
pub(crate) fn clear_network_manager_redirect(
    commands: &dyn DnsCommands,
    files: &DnsFiles,
) -> Result<(), PlatformError> {
    let drop_in = files.nm_drop_in();
    if !drop_in.exists() {
        return Ok(());
    }
    std::fs::remove_file(&drop_in).map_err(|e| PlatformError::Transient {
        operation: "remove the NetworkManager DNS drop-in",
        detail: e.to_string(),
    })?;
    reload(commands)
}

/// The devices' own servers, which the global setting does not touch.
pub struct NetworkManagerDnsServers<C: DnsCommands>(pub C);

impl<C: DnsCommands> SystemDnsServersPort for NetworkManagerDnsServers<C> {
    fn upstream_candidates_v4(&self) -> Vec<UpstreamDnsCandidate> {
        let mut out: Vec<UpstreamDnsCandidate> = Vec::new();
        for device in devices(&self.0) {
            let index = super::link_index(&device.name);
            for server in forwardable(device.dns) {
                if out.iter().any(|c| c.server == server) {
                    continue;
                }
                out.push(UpstreamDnsCandidate::new(index, server));
            }
        }
        out
    }
}

/// The devices' search domains, each with the servers of its device.
pub struct NetworkManagerDnsScopes<C: DnsCommands>(pub C);

impl<C: DnsCommands> InterfaceDnsScopePort for NetworkManagerDnsScopes<C> {
    fn dns_scopes(&self) -> Vec<InterfaceDnsScope> {
        devices(&self.0)
            .into_iter()
            .flat_map(|device| {
                let NmDevice { name, dns, domains } = device;
                domains.into_iter().map(move |suffix| InterfaceDnsScope {
                    adapter_id: name.clone(),
                    display_name: name.clone(),
                    suffix,
                    servers: dns.clone(),
                })
            })
            .collect()
    }
}
