//! Controlled import pipeline types.
//!
//! A controlled import is the only way external configuration enters the
//! revision store. External files never become active policy directly —
//! they must pass through parse/validate/canonicalize (performed by the
//! caller) and then through this pipeline, which creates a [`PendingRevision`].
//!
//! # Pipeline stages
//!
//! 1. **Acquisition** (caller): read file, check size, compute `file_hash`.
//! 2. **Parse/validate** (caller, format-specific): txt file parser;
//!    YAML preset parser.
//! 3. **Canonicalize** (caller, [`crate::validation`]): → [`crate::canonical::CanonicalProfile`].
//! 4. **Candidate build** (this module, [`process_import`]): → [`PendingRevision`].
//!
//! The pipeline function [`process_import`] is pure domain logic: no I/O, no
//! timestamps generated internally, no UUID generation. All inputs are supplied
//! by the caller so the pipeline is deterministic and testable.
//!
//! # Format-agnostic design
//!
//! The pipeline operates on a [`CanonicalProfile`] — the post-parse, post-validate
//! normalized form. The parse stage is format-specific and lives outside this module,
//! allowing YAML preset parsing to be added without touching the pipeline.

use crate::canonical::CanonicalProfile;
use crate::revision::{
    ContentHash, ImportChannel, ImportedArtifact, IntegrityStatus, PendingRevision, PolicyRevision,
    RevisionActor, RevisionId, RevisionSeq, RevisionSource, RiskLevel, UnixTimestamp,
};

/// Room reserved inside one IPC frame for everything that is not the file:
/// the envelope (operation, ids, class, token), the mutation payload's own
/// fields, and JSON punctuation. Generous on purpose — the cost of over-
/// reserving is a slightly smaller allowed file, the cost of under-reserving
/// is a refusal from the wrong layer.
const IMPORT_ENVELOPE_HEADROOM_BYTES: usize = 16 * 1024;

/// Maximum permitted raw rules file size for a controlled import.
///
/// Files exceeding this limit must be rejected during acquisition (before
/// parsing), not inside the domain pipeline.
///
/// DERIVED from the transport ceiling rather than set beside it. A preset
/// travels base64-wrapped inside a JSON envelope, so the wire costs 4 bytes
/// per 3 bytes of file. While this was a flat 1 MiB — the frame limit itself —
/// every file above roughly three quarters of it passed the domain check and
/// was then refused by the transport as "frame too large": a refusal from the
/// wrong layer, in the wrong words, for a file the product said was fine.
pub const IMPORT_FILE_SIZE_LIMIT_BYTES: u64 =
    ((nrr_shared::ipc_transport::IPC_MAX_MESSAGE_BYTES - IMPORT_ENVELOPE_HEADROOM_BYTES) / 4 * 3)
        as u64;

/// The user-facing action that triggered this import.
///
/// Both variants use [`ImportChannel::Snapshot`] semantics: file content is
/// captured at acquisition time; subsequent changes to the source file do not
/// affect the stored revision.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum ImportTrigger {
    /// User selected a new rules file via the file picker (`LoadRuleList` action).
    ///
    /// The `source_path` in the accompanying [`ImportRequest`] becomes the new
    /// configured rules file path.
    NewFile,
    /// User triggered a re-read of the currently configured rules file
    /// (`UpdateRulesFromFile` action).
    ///
    /// The source path does not change; only the content is re-read.
    CurrentFile,
}

impl ImportTrigger {
    /// Stable slug for logging, audit events, and IPC provenance fields.
    pub const fn slug(self) -> &'static str {
        match self {
            Self::NewFile => "new-file",
            Self::CurrentFile => "current-file",
        }
    }
}

/// Canonical import request.
///
/// The caller completes pipeline stages 1–3 before constructing this request:
/// reading the file, computing both hash fields, parsing, and canonicalizing.
/// [`process_import`] then performs stage 4 (candidate build) with no I/O.
///
/// # Hash fields
///
/// - `file_hash`: SHA-256 of the raw file bytes at acquisition time.
///   Allows verifying the file was not modified between acquisition and parsing.
/// - `content_hash`: SHA-256 of the canonical content (covering `rule_book`,
///   `primary`, `secondary`, `behavior_mode`).
///   Used for deduplication and `PolicyRevision` integrity checks.
///   In the scaffold phase the caller supplies a deterministic placeholder;
///   real canonical SHA-256 is wired by the service layer.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct ImportRequest {
    /// Unique identifier for the candidate revision to be created.
    ///
    /// Generated by the caller (service or GUI backend). Must conform to
    /// `"rev-{non-empty-suffix}"` format as defined by [`RevisionId`].
    pub revision_id: RevisionId,
    /// Monotonic sequence number for this candidate revision.
    pub seq: RevisionSeq,
    /// Absolute path to the source file, stored for provenance only.
    pub source_path: String,
    /// SHA-256 of the raw file bytes at acquisition time.
    pub file_hash: ContentHash,
    /// SHA-256 of the serialized canonical policy content.
    pub content_hash: ContentHash,
    /// UTC timestamp when the file was acquired.
    pub acquired_at: UnixTimestamp,
    /// The action that triggered this import.
    pub trigger: ImportTrigger,
    /// Who initiated this import.
    pub actor: RevisionActor,
    /// Already-parsed and canonicalized policy content (pipeline stages 1–3 complete).
    pub content: CanonicalProfile,
    /// ID of the pending revision displaced by this import (variant A supersession).
    ///
    /// `None` if no pending revision existed at import time.
    pub displaces_pending_id: Option<RevisionId>,
}

/// Outcome of a controlled import pipeline run.
///
/// The pipeline never modifies the active revision. [`PendingReview`](Self::PendingReview)
/// must be explicitly confirmed by the user before the service may activate it.
// `PendingReview` carries a full `PendingRevision`, dwarfing the other
// variants. Boxing it would add a heap allocation on the common import-
// succeeds path for a value that is constructed, matched, and dropped
// immediately (never stored in bulk), so the size difference is irrelevant
// here while the allocation would not be.
#[allow(clippy::large_enum_variant)]
#[non_exhaustive]
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum ImportResult {
    /// The artifact's canonical content is identical to the current active revision.
    ///
    /// No candidate is created. The caller should record an informational audit
    /// event and notify the user that the file is already in sync.
    NoChange,
    /// Import produced a candidate revision now awaiting user review and
    /// explicit confirmation before the service may activate it.
    PendingReview(PendingRevision),
    /// The artifact was rejected before a candidate could be created.
    ///
    /// The active revision is unchanged. The caller must surface a user-visible
    /// error using the reason.
    Rejected(ImportRejectedReason),
    /// A non-content error prevented the import from completing.
    ///
    /// Distinct from [`Rejected`](Self::Rejected): the source file may be valid
    /// and retrying may succeed (e.g. the file was temporarily locked).
    Failed { description: String },
}

impl ImportResult {
    /// Returns `true` when the artifact matched the active revision exactly.
    pub fn is_no_change(&self) -> bool {
        matches!(self, Self::NoChange)
    }

    /// Returns the pending revision if the import produced one.
    pub fn pending_revision(&self) -> Option<&PendingRevision> {
        if let Self::PendingReview(rev) = self {
            Some(rev)
        } else {
            None
        }
    }
}

/// Why an import artifact was rejected before a candidate revision could be built.
#[non_exhaustive]
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum ImportRejectedReason {
    /// The content hash matches an already-pending candidate (deduplication).
    ///
    /// The existing pending revision is unchanged; no new candidate is created.
    DuplicatePending,
    /// The total rule count exceeds the Free edition maximum.
    TooManyRules { count: u32, limit: u32 },
}

/// Runs the domain import pipeline and returns an [`ImportResult`].
///
/// This function is pure: no I/O, no mutable state, no UUID/timestamp generation.
/// All inputs come from the caller.
///
/// # Arguments
///
/// - `request` — fully constructed import request (pipeline stages 1–3 done).
/// - `active_content_hash` — content hash of the currently active revision.
///   `None` when no active revision exists yet.
/// - `pending_content_hash` — content hash of the currently pending candidate.
///   `None` when no candidate is pending.
///
/// # Invariants
///
/// - The active revision is never modified regardless of the outcome.
/// - Risk level is set to [`RiskLevel::Low`] as a baseline; enriched risk
///   scoring is layered on separately.
/// - `diff_summary` is `None` on the candidate; computed separately.
pub fn process_import(
    request: ImportRequest,
    active_content_hash: Option<&ContentHash>,
    pending_content_hash: Option<&ContentHash>,
) -> ImportResult {
    // Idempotency: same canonical content as the active revision → no-change.
    if active_content_hash == Some(&request.content_hash) {
        return ImportResult::NoChange;
    }

    // Deduplication: same canonical content already pending → reject quietly.
    if pending_content_hash == Some(&request.content_hash) {
        return ImportResult::Rejected(ImportRejectedReason::DuplicatePending);
    }

    let artifact = ImportedArtifact {
        source_path: request.source_path,
        file_hash: request.file_hash,
        imported_at: request.acquired_at,
        channel: ImportChannel::Snapshot,
    };

    let candidate = PolicyRevision {
        id: request.revision_id,
        seq: request.seq,
        created_at: request.acquired_at,
        source: RevisionSource::Import(artifact),
        actor: request.actor,
        content: request.content,
        content_hash: request.content_hash,
        diff_summary: None,         // TODO: computed by diff engine
        risk_level: RiskLevel::Low, // TODO: enriched by risk scoring
        integrity_status: IntegrityStatus::Verified,
    };

    let pending = PendingRevision {
        candidate,
        queued_at: request.acquired_at,
        displaced_revision_id: request.displaces_pending_id,
    };

    ImportResult::PendingReview(pending)
}

#[cfg(test)]
#[allow(clippy::expect_used)]
mod tests {
    use super::*;
    use crate::{
        canonical::{CanonicalProfile, CanonicalRuleBook},
        AdapterIdentity, BindingSource, RouteBehaviorMode, RouteBinding, RouteRole,
    };

    fn mock_profile() -> CanonicalProfile {
        CanonicalProfile {
            primary: RouteBinding {
                role: RouteRole::Primary,
                adapter: AdapterIdentity {
                    stable_id: "adapter-aa:bb:cc:dd:ee:01-1".to_string(),
                    display_name: "Primary Adapter".to_string(),
                },
                source: BindingSource::UserAssigned,
            },
            secondary: None,
            behavior_mode: RouteBehaviorMode::StrictSecondaryFailClosed,
            rule_book: CanonicalRuleBook::default(),
        }
    }

    fn mock_request_with_hash(content_hash_byte: u8) -> ImportRequest {
        ImportRequest {
            revision_id: RevisionId::from_prefixed_string("rev-test-import-001".to_string())
                .expect("valid id"),
            seq: RevisionSeq::FIRST,
            source_path: "/path/to/rules_primary.txt".to_string(),
            file_hash: ContentHash::from_bytes([0xaa; 32]),
            content_hash: ContentHash::from_bytes([content_hash_byte; 32]),
            acquired_at: UnixTimestamp::from_secs(1_700_000_000),
            trigger: ImportTrigger::NewFile,
            actor: RevisionActor::LocalUser,
            content: mock_profile(),
            displaces_pending_id: None,
        }
    }

    #[test]
    fn no_change_when_content_hash_matches_active() {
        let req = mock_request_with_hash(0x42);
        let active = ContentHash::from_bytes([0x42; 32]);
        assert!(process_import(req, Some(&active), None).is_no_change());
    }

    #[test]
    fn pending_review_when_content_differs_from_active() {
        let active = ContentHash::from_bytes([0x11; 32]);
        let req = mock_request_with_hash(0x22);
        let result = process_import(req, Some(&active), None);
        assert!(result.pending_revision().is_some());
    }

    #[test]
    fn pending_review_when_no_active_revision() {
        let result = process_import(mock_request_with_hash(0x33), None, None);
        assert!(result.pending_revision().is_some());
    }

    #[test]
    fn rejected_when_duplicate_pending() {
        let pending_hash = ContentHash::from_bytes([0x44; 32]);
        let req = mock_request_with_hash(0x44);
        let result = process_import(req, None, Some(&pending_hash));
        assert!(matches!(
            result,
            ImportResult::Rejected(ImportRejectedReason::DuplicatePending)
        ));
    }

    #[test]
    fn no_change_takes_priority_over_duplicate_pending() {
        let hash = ContentHash::from_bytes([0x55; 32]);
        let req = mock_request_with_hash(0x55);
        // active matches → no-change, even if pending would also match
        let result = process_import(req, Some(&hash), Some(&hash));
        assert!(result.is_no_change());
    }

    #[test]
    fn current_file_trigger_produces_pending_review() {
        let mut req = mock_request_with_hash(0x66);
        req.trigger = ImportTrigger::CurrentFile;
        let result = process_import(req, None, None);
        let pending = result.pending_revision().expect("should be pending");
        assert_eq!(
            pending.candidate.source,
            crate::revision::RevisionSource::Import(ImportedArtifact {
                source_path: "/path/to/rules_primary.txt".to_string(),
                file_hash: ContentHash::from_bytes([0xaa; 32]),
                imported_at: UnixTimestamp::from_secs(1_700_000_000),
                channel: ImportChannel::Snapshot,
            })
        );
    }

    #[test]
    fn import_trigger_slugs_are_stable() {
        assert_eq!(ImportTrigger::NewFile.slug(), "new-file");
        assert_eq!(ImportTrigger::CurrentFile.slug(), "current-file");
    }

    /// The cap must be small enough that the file, base64-wrapped, still
    /// leaves room for the envelope inside ONE frame. Otherwise the domain says
    /// yes and the transport says "frame too large" — the exact split the
    /// derivation exists to close. The realistic envelope is measured in
    /// `nrr-service-runtime`, which is where a frame is actually built; this
    /// crate keeps no JSON or base64 dependency to do it here.
    #[test]
    fn the_largest_accepted_import_still_fits_one_frame() {
        const FRAME: usize = nrr_shared::ipc_transport::IPC_MAX_MESSAGE_BYTES;
        // base64 emits 4 characters per 3 input bytes, rounded up.
        let encoded = (IMPORT_FILE_SIZE_LIMIT_BYTES as usize).div_ceil(3) * 4;
        assert!(
            encoded + IMPORT_ENVELOPE_HEADROOM_BYTES <= FRAME,
            "a maximum-size import encodes to {encoded} bytes, which with the              {IMPORT_ENVELOPE_HEADROOM_BYTES} byte envelope allowance exceeds the              {FRAME} byte frame"
        );

        // Positive control: the flat one-frame cap this replaced does NOT fit,
        // so the assertion above tests the derivation rather than a frame limit
        // roomy enough to swallow anything.
        assert!(FRAME.div_ceil(3) * 4 + IMPORT_ENVELOPE_HEADROOM_BYTES > FRAME);
    }
}
