//! Revision identity and provenance: [`RevisionId`], [`ContentHash`],
//! [`UnixTimestamp`], [`RevisionSource`] and [`RiskLevel`]. The revision
//! lifecycle itself is `rules_revision` and the storage layer's; the audit
//! trail is `nrr-diagnostics`.

use core::fmt;

// ── RevisionId ────────────────────────────────────────────────────────────────

/// Human-readable, prefixed-UUID identifier for a policy revision.
///
/// Format: `"rev-{uuid_v4}"`, e.g.
/// `"rev-550e8400-e29b-41d4-a716-446655440000"`.
///
/// The `rev-` prefix disambiguates revision IDs from rule IDs (`r-`) and other
/// entity identifiers in logs and audit events.
///
/// IDs are generated by the service. This type is a value-object
/// wrapper that guarantees the prefix convention without imposing UUID
/// generation constraints on the domain layer.
#[derive(Clone, Debug, PartialEq, Eq, Hash)]
pub struct RevisionId(String);

impl RevisionId {
    const PREFIX: &'static str = "rev-";

    /// Constructs a `RevisionId` from a pre-formatted prefixed string.
    ///
    /// Returns `Err` if the string does not start with `"rev-"` or if the
    /// remainder after the prefix is empty.
    pub fn from_prefixed_string(id: String) -> Result<Self, &'static str> {
        let suffix = id
            .strip_prefix(Self::PREFIX)
            .ok_or("revision id must start with \"rev-\"")?;
        if suffix.is_empty() {
            return Err("revision id suffix must not be empty");
        }
        Ok(Self(id))
    }

    /// Returns the full identifier string including the `"rev-"` prefix.
    pub fn as_str(&self) -> &str {
        &self.0
    }

    /// Returns the suffix after the `"rev-"` prefix (the UUID component).
    pub fn uuid_part(&self) -> &str {
        // Safety: `from_prefixed_string` guarantees the prefix is present.
        &self.0[Self::PREFIX.len()..]
    }
}

impl fmt::Display for RevisionId {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(&self.0)
    }
}

// ── ContentHash ───────────────────────────────────────────────────────────────

/// SHA-256 fingerprint of a revision's policy content: bindings, behavior
/// mode and rule book, never labels or timestamps, so identical policy hashes
/// alike however it was created. Computed by the service; this type holds it.
#[derive(Clone, PartialEq, Eq, Hash)]
pub struct ContentHash([u8; 32]);

impl ContentHash {
    /// Wraps a raw 32-byte SHA-256 digest.
    pub fn from_bytes(bytes: [u8; 32]) -> Self {
        Self(bytes)
    }

    /// Returns the raw 32-byte digest.
    pub fn as_bytes(&self) -> &[u8; 32] {
        &self.0
    }

    /// Returns the hash as a lowercase hex string (64 characters).
    pub fn to_hex_string(&self) -> String {
        self.0.iter().fold(String::with_capacity(64), |mut acc, b| {
            use fmt::Write as _;
            let _ = write!(acc, "{b:02x}");
            acc
        })
    }

    /// Parses a lowercase or uppercase 64-character hex string.
    ///
    /// Returns `Err` if the string is not exactly 64 hex characters.
    pub fn from_hex_string(hex: &str) -> Result<Self, &'static str> {
        if hex.len() != 64 {
            return Err("content hash hex string must be exactly 64 characters");
        }
        let mut bytes = [0u8; 32];
        for (i, chunk) in hex.as_bytes().chunks(2).enumerate() {
            let hi = hex_nibble(chunk[0])?;
            let lo = hex_nibble(chunk[1])?;
            bytes[i] = (hi << 4) | lo;
        }
        Ok(Self(bytes))
    }
}

fn hex_nibble(c: u8) -> Result<u8, &'static str> {
    match c {
        b'0'..=b'9' => Ok(c - b'0'),
        b'a'..=b'f' => Ok(c - b'a' + 10),
        b'A'..=b'F' => Ok(c - b'A' + 10),
        _ => Err("invalid hex character in content hash"),
    }
}

impl fmt::Debug for ContentHash {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "ContentHash({})", self.to_hex_string())
    }
}

impl fmt::Display for ContentHash {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(&self.to_hex_string())
    }
}

// ── UnixTimestamp ─────────────────────────────────────────────────────────────

/// UTC seconds since the Unix epoch. A newtype so the unit cannot be mixed up
/// with other `u64` quantities.
#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct UnixTimestamp(u64);

impl UnixTimestamp {
    /// Constructs a `UnixTimestamp` from raw seconds since epoch.
    pub fn from_secs(secs: u64) -> Self {
        Self(secs)
    }

    /// Returns the raw seconds value.
    pub fn as_secs(self) -> u64 {
        self.0
    }
}

impl fmt::Display for UnixTimestamp {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{}", self.0)
    }
}

// ── RevisionSource ────────────────────────────────────────────────────────────

/// How a policy revision was created; an input to risk scoring.
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum RevisionSource {
    /// User saved changes directly via the GUI (add/edit/delete rule, adapter
    /// selection, behavior mode change). Narrow interactive flow — may activate
    /// immediately after service validation and audit logging.
    DirectEdit,
    /// Rules file changed on disk and the change was applied via the
    /// "Update rules from file" button (Notify mode) or auto-applied (AutoApply
    /// mode). Treated the same as a direct edit for activation purposes when
    /// explicitly confirmed by the user.
    FileSync,
}

// ── RiskLevel ─────────────────────────────────────────────────────────────────

/// Basic risk classification assigned to a candidate revision.
///
/// Assigned by the service before the candidate is stored. Higher risk
/// levels require more explicit user review and generate persistent alerts
/// until acknowledged. See `SECURITY.md §Review and Approval Flow`.
///
/// # Criteria (from SECURITY.md)
///
/// | Level    | Examples                                                          |
/// |----------|-------------------------------------------------------------------|
/// | `Low`    | A small number of exact FQDN additions.                          |
/// | `Medium` | Broader wildcard/suffix changes; app-rule additions.             |
/// | `High`   | Default route changes, mass changes, rerouting known destinations|
/// |          | to secondary, interface binding changes.                         |
///
/// All `High`-risk and non-interactive external-origin changes must keep a
/// persistent alert until the user reviews or resolves the change.
#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum RiskLevel {
    /// A small number of exact FQDN additions. No structural changes.
    Low,
    /// Broader domain/suffix changes or application-rule additions.
    Medium,
    /// Default route changes, mass changes, interface binding changes,
    /// or rerouting known destinations to secondary.
    High,
    /// Catastrophic configurations: the candidate
    /// would lock the user out of the network (e.g. primary↔secondary
    /// swap under `StrictSecondaryFailClosed` with no fallback). Today
    /// no signal in `score_candidate` is severe enough to map here —
    /// the level is wire-stable so future binding-aware detection can
    /// emit it without changing the IPC contract. `PartialOrd` puts
    /// `Critical` above `High`, so `signals.iter().map(level).max()`
    /// naturally returns it once present.
    Critical,
}

impl RiskLevel {
    pub const fn as_slug(self) -> &'static str {
        match self {
            Self::Low => "low",
            Self::Medium => "medium",
            Self::High => "high",
            Self::Critical => "critical",
        }
    }
}

impl fmt::Display for RiskLevel {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(self.as_slug())
    }
}

// Cross-crate projections to/from `nrr-shared::ReviewRiskLevel`. The IPC DTO
// type lives in `nrr-shared` because the dependency direction is
// `domain → shared`; the canonical conversion lives here so callers in
// service-runtime have a single import point for marshalling.
impl From<nrr_shared::ipc_dto::ReviewRiskLevel> for RiskLevel {
    fn from(dto: nrr_shared::ipc_dto::ReviewRiskLevel) -> Self {
        match dto {
            nrr_shared::ipc_dto::ReviewRiskLevel::Low => Self::Low,
            nrr_shared::ipc_dto::ReviewRiskLevel::Medium => Self::Medium,
            nrr_shared::ipc_dto::ReviewRiskLevel::High => Self::High,
            nrr_shared::ipc_dto::ReviewRiskLevel::Critical => Self::Critical,
        }
    }
}

impl From<RiskLevel> for nrr_shared::ipc_dto::ReviewRiskLevel {
    fn from(level: RiskLevel) -> Self {
        match level {
            RiskLevel::Low => Self::Low,
            RiskLevel::Medium => Self::Medium,
            RiskLevel::High => Self::High,
            RiskLevel::Critical => Self::Critical,
        }
    }
}

// Bridge to the parallel `ipc_payloads::ReviewRiskLevel`
// enum (wire-form, serde-enabled). The two enums exist for historical
// reasons (`ipc_dto` is the older shape, `ipc_payloads` is the
// kebab-case serde version); both carry the same four levels.
impl From<RiskLevel> for nrr_shared::ipc_payloads::ReviewRiskLevel {
    fn from(level: RiskLevel) -> Self {
        match level {
            RiskLevel::Low => Self::Low,
            RiskLevel::Medium => Self::Medium,
            RiskLevel::High => Self::High,
            RiskLevel::Critical => Self::Critical,
        }
    }
}

// ── Tests ─────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests;
