//! Revision identity model and provenance types for the policy revision system.
//!
//! This module defines the foundational types for the revision system:
//! - [`RevisionId`] — human-readable, prefixed-UUID identifier for a revision.
//! - [`RevisionSeq`] — monotonic sequence number assigned by the service.
//! - [`ContentHash`] — SHA-256 fingerprint over policy-content fields.
//! - [`UnixTimestamp`] — UTC Unix timestamp (seconds since epoch).
//! - [`ImportChannel`] — how an artifact was imported.
//! - [`ImportedArtifact`] — provenance record for an externally imported config.
//!
//! [`crate::canonical::CanonicalProfile`] is the input type consumed by
//! `PolicyRevision`. It is produced by the
//! validation pipeline and carries all policy-relevant content
//! in a normalized form. The content hash in each `PolicyRevision` is computed
//! over its `CanonicalProfile` fields.
//!
//! # SHA-256 hash scope
//!
//! `ContentHash` covers exactly: `primary` binding + `secondary` binding +
//! `behavior_mode` + `rule_book`. Display labels, import metadata, actor
//! identity, and timestamps are excluded from the hash. This ensures that two
//! configurations with the same routing policy produce the same fingerprint
//! regardless of how they were labeled or when they were imported.
//!
//! Actual SHA-256 computation is performed by the service layer.
//! This module defines the type boundary only.

use core::fmt;

// `CanonicalProfile` is the policy-content input consumed by `PolicyRevision`.
// Re-export here so revision-system consumers can access it from one location.
pub use crate::canonical::CanonicalProfile;

// ── RevisionId ────────────────────────────────────────────────────────────────

/// Human-readable, prefixed-UUID identifier for a policy revision.
///
/// Format: `"rev-{uuid_v4}"`, e.g.
/// `"rev-550e8400-e29b-41d4-a716-446655440000"`.
///
/// The `rev-` prefix disambiguates revision IDs from rule IDs (`r-`) and other
/// entity identifiers in logs and audit events.
///
/// IDs are generated by the service. This type is a value-object
/// wrapper that guarantees the prefix convention without imposing UUID
/// generation constraints on the domain layer.
#[derive(Clone, Debug, PartialEq, Eq, Hash)]
pub struct RevisionId(String);

impl RevisionId {
    const PREFIX: &'static str = "rev-";

    /// Constructs a `RevisionId` from a pre-formatted prefixed string.
    ///
    /// Returns `Err` if the string does not start with `"rev-"` or if the
    /// remainder after the prefix is empty.
    pub fn from_prefixed_string(id: String) -> Result<Self, &'static str> {
        let suffix = id
            .strip_prefix(Self::PREFIX)
            .ok_or("revision id must start with \"rev-\"")?;
        if suffix.is_empty() {
            return Err("revision id suffix must not be empty");
        }
        Ok(Self(id))
    }

    /// Returns the full identifier string including the `"rev-"` prefix.
    pub fn as_str(&self) -> &str {
        &self.0
    }

    /// Returns the suffix after the `"rev-"` prefix (the UUID component).
    pub fn uuid_part(&self) -> &str {
        // Safety: `from_prefixed_string` guarantees the prefix is present.
        &self.0[Self::PREFIX.len()..]
    }
}

impl fmt::Display for RevisionId {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(&self.0)
    }
}

// ── RevisionSeq ───────────────────────────────────────────────────────────────

/// Monotonically increasing sequence number assigned to each revision.
///
/// Sequences start at `1`. The service increments the counter for every new
/// revision, including pending candidates that are later rejected. This allows
/// detection of gaps (e.g. from an externally truncated audit log).
///
/// Persistent storage and counter management are implemented by the service layer.
#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct RevisionSeq(u64);

impl RevisionSeq {
    /// The first valid sequence number.
    pub const FIRST: Self = Self(1);

    /// Constructs a `RevisionSeq` from a raw `u64`. Must be `>= 1`.
    pub fn new(value: u64) -> Result<Self, &'static str> {
        if value == 0 {
            Err("revision sequence number must be >= 1")
        } else {
            Ok(Self(value))
        }
    }

    /// Returns the raw sequence value.
    pub fn value(self) -> u64 {
        self.0
    }

    /// Returns the next sequence number, or `None` on overflow.
    ///
    /// Overflow is physically impossible in practice (u64::MAX revisions at
    /// one per nanosecond would require ~584 years), but the type signature
    /// is honest rather than panicking.
    pub fn next(self) -> Option<Self> {
        self.0.checked_add(1).map(Self)
    }
}

impl fmt::Display for RevisionSeq {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{}", self.0)
    }
}

// ── ContentHash ───────────────────────────────────────────────────────────────

/// SHA-256 content fingerprint of a policy revision.
///
/// Computed over the canonical policy fields of a [`CanonicalProfile`]:
/// `primary` + `secondary` + `behavior_mode` + `rule_book`.
///
/// # Excluded fields
///
/// Display labels (`route_primary_label`, `route_secondary_label`), import
/// metadata, actor identity, and timestamps are **not** included in the hash.
/// Two configurations with identical routing policy always produce the same
/// `ContentHash` regardless of when or how they were created.
///
/// # Computation
///
/// SHA-256 computation is implemented by the service layer.
/// This type holds the result; it does not perform the computation.
///
/// # Integrity
///
/// The hash is stored separately from the content it covers. The service
/// verifies integrity by recomputing the hash on load and comparing with the
/// stored value. Reserve under HMAC with a service-owned key is planned for
/// a future version.
#[derive(Clone, PartialEq, Eq, Hash)]
pub struct ContentHash([u8; 32]);

impl ContentHash {
    /// Wraps a raw 32-byte SHA-256 digest.
    pub fn from_bytes(bytes: [u8; 32]) -> Self {
        Self(bytes)
    }

    /// Returns the raw 32-byte digest.
    pub fn as_bytes(&self) -> &[u8; 32] {
        &self.0
    }

    /// Returns the hash as a lowercase hex string (64 characters).
    pub fn to_hex_string(&self) -> String {
        self.0.iter().fold(String::with_capacity(64), |mut acc, b| {
            use fmt::Write as _;
            let _ = write!(acc, "{b:02x}");
            acc
        })
    }

    /// Parses a lowercase or uppercase 64-character hex string.
    ///
    /// Returns `Err` if the string is not exactly 64 hex characters.
    pub fn from_hex_string(hex: &str) -> Result<Self, &'static str> {
        if hex.len() != 64 {
            return Err("content hash hex string must be exactly 64 characters");
        }
        let mut bytes = [0u8; 32];
        for (i, chunk) in hex.as_bytes().chunks(2).enumerate() {
            let hi = hex_nibble(chunk[0])?;
            let lo = hex_nibble(chunk[1])?;
            bytes[i] = (hi << 4) | lo;
        }
        Ok(Self(bytes))
    }
}

fn hex_nibble(c: u8) -> Result<u8, &'static str> {
    match c {
        b'0'..=b'9' => Ok(c - b'0'),
        b'a'..=b'f' => Ok(c - b'a' + 10),
        b'A'..=b'F' => Ok(c - b'A' + 10),
        _ => Err("invalid hex character in content hash"),
    }
}

impl fmt::Debug for ContentHash {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "ContentHash({})", self.to_hex_string())
    }
}

impl fmt::Display for ContentHash {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(&self.to_hex_string())
    }
}

// ── UnixTimestamp ─────────────────────────────────────────────────────────────

/// UTC Unix timestamp, expressed as seconds since the Unix epoch (1970-01-01).
///
/// Used for `ImportedArtifact::imported_at` and `PolicyRevision::created_at`.
/// The service layer supplies the value; this type is a thin
/// newtype that makes the unit explicit and prevents accidental mixing with
/// other `u64` quantities.
#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct UnixTimestamp(u64);

impl UnixTimestamp {
    /// Constructs a `UnixTimestamp` from raw seconds since epoch.
    pub fn from_secs(secs: u64) -> Self {
        Self(secs)
    }

    /// Returns the raw seconds value.
    pub fn as_secs(self) -> u64 {
        self.0
    }
}

impl fmt::Display for UnixTimestamp {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{}", self.0)
    }
}

// ── ImportChannel ─────────────────────────────────────────────────────────────

/// How a configuration artifact was imported.
///
/// `Snapshot` is the only implemented import mode in the Free edition.
/// `Linked` is reserved in the type system for future use but must not be
/// passed to any live code path — attempts to use `Linked` channels are
/// treated as a programming error.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum ImportChannel {
    /// The external file was read and its content was copied into the
    /// revision store at import time. The original file path is recorded
    /// for provenance only; future changes to the file do not affect the
    /// stored revision.
    Snapshot,
    /// Reserved for a future "linked import" mode where the service tracks
    /// the external file and automatically detects changes. Not implemented
    /// in the Free edition.
    Linked,
}

// ── ImportedArtifact ──────────────────────────────────────────────────────────

/// Provenance record for a configuration imported from an external file.
///
/// Attached to a `PolicyRevision` when the revision originates from an
/// external source (a YAML preset file, a Full Settings export, or a
/// manually prepared config). Revisions created by direct GUI edits do not
/// carry an `ImportedArtifact`.
///
/// # Hash coverage
///
/// `file_hash` is the SHA-256 of the raw file bytes at the time of import.
/// It is distinct from `ContentHash` in `PolicyRevision`: `file_hash` covers
/// the serialized file format; `ContentHash` covers the deserialized,
/// normalized canonical policy content.
///
/// Both hashes are stored so that:
/// - `file_hash` can verify that the imported file was not tampered with
///   before parsing.
/// - `ContentHash` can detect semantic equivalence across different file
///   representations of the same policy.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct ImportedArtifact {
    /// Human-readable source description.
    ///
    /// For file imports: the absolute or relative path to the imported file.
    /// For clipboard or other non-file sources: a descriptive label.
    pub source_path: String,
    /// SHA-256 hash of the raw file bytes at import time.
    pub file_hash: ContentHash,
    /// UTC timestamp when the import was initiated.
    pub imported_at: UnixTimestamp,
    /// Import mode. `Linked` is reserved; only `Snapshot` is implemented.
    pub channel: ImportChannel,
}

// ── RevisionSource ────────────────────────────────────────────────────────────

/// How a policy revision was created.
///
/// `source` is recorded in `PolicyRevision` for audit and review-flow purposes.
/// It determines whether a revision requires `PendingRevision` review before
/// activation (imported / file-sync) or may activate immediately (direct GUI
/// edit within narrow approved flows).
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum RevisionSource {
    /// User saved changes directly via the GUI (add/edit/delete rule, adapter
    /// selection, behavior mode change). Narrow interactive flow — may activate
    /// immediately after service validation and audit logging.
    DirectEdit,
    /// Rules file changed on disk and the change was applied via the
    /// "Update rules from file" button (Notify mode) or auto-applied (AutoApply
    /// mode). Treated the same as a direct edit for activation purposes when
    /// explicitly confirmed by the user.
    FileSync,
    /// Configuration was imported from an external file. Requires
    /// `PendingRevision` review before activation (non-interactive origin).
    Import(ImportedArtifact),
}

// ── RevisionActor ─────────────────────────────────────────────────────────────

/// Who initiated the revision-related action.
///
/// In the Free edition all interactive actions are `LocalUser`. `Service` is
/// used for automated actions: periodic integrity checks, auto-apply of file
/// changes, and rollback triggered by the service watchdog.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum RevisionActor {
    /// The local user acting through the GUI.
    LocalUser,
    /// The background Windows service acting autonomously.
    Service,
}

// ── RiskLevel ─────────────────────────────────────────────────────────────────

/// Basic risk classification assigned to a candidate `PolicyRevision`.
///
/// Assigned by the service before creating a `PolicyRevision`. Higher risk
/// levels require more explicit user review and generate persistent alerts
/// until acknowledged. See `SECURITY.md §Review and Approval Flow`.
///
/// # Criteria (from SECURITY.md)
///
/// | Level    | Examples                                                          |
/// |----------|-------------------------------------------------------------------|
/// | `Low`    | A small number of exact FQDN additions.                          |
/// | `Medium` | Broader wildcard/suffix changes; app-rule additions.             |
/// | `High`   | Default route changes, mass changes, rerouting known destinations|
/// |          | to secondary, interface binding changes.                         |
///
/// All `High`-risk and non-interactive external-origin changes must keep a
/// persistent alert until the user reviews or resolves the change.
#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum RiskLevel {
    /// A small number of exact FQDN additions. No structural changes.
    Low,
    /// Broader domain/suffix changes or application-rule additions.
    Medium,
    /// Default route changes, mass changes, interface binding changes,
    /// or rerouting known destinations to secondary.
    High,
    /// Catastrophic configurations: the candidate
    /// would lock the user out of the network (e.g. primary↔secondary
    /// swap under `StrictSecondaryFailClosed` with no fallback). Today
    /// no signal in `score_candidate` is severe enough to map here —
    /// the level is wire-stable so future binding-aware detection can
    /// emit it without changing the IPC contract. `PartialOrd` puts
    /// `Critical` above `High`, so `signals.iter().map(level).max()`
    /// naturally returns it once present.
    Critical,
}

impl fmt::Display for RiskLevel {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Low => f.write_str("low"),
            Self::Medium => f.write_str("medium"),
            Self::High => f.write_str("high"),
            Self::Critical => f.write_str("critical"),
        }
    }
}

// Cross-crate projections to/from `nrr-shared::ReviewRiskLevel`. The IPC DTO
// type lives in `nrr-shared` because the dependency direction is
// `domain → shared`; the canonical conversion lives here so callers in
// service-runtime have a single import point for marshalling.
impl From<nrr_shared::ipc_dto::ReviewRiskLevel> for RiskLevel {
    fn from(dto: nrr_shared::ipc_dto::ReviewRiskLevel) -> Self {
        match dto {
            nrr_shared::ipc_dto::ReviewRiskLevel::Low => Self::Low,
            nrr_shared::ipc_dto::ReviewRiskLevel::Medium => Self::Medium,
            nrr_shared::ipc_dto::ReviewRiskLevel::High => Self::High,
            nrr_shared::ipc_dto::ReviewRiskLevel::Critical => Self::Critical,
        }
    }
}

impl From<RiskLevel> for nrr_shared::ipc_dto::ReviewRiskLevel {
    fn from(level: RiskLevel) -> Self {
        match level {
            RiskLevel::Low => Self::Low,
            RiskLevel::Medium => Self::Medium,
            RiskLevel::High => Self::High,
            RiskLevel::Critical => Self::Critical,
        }
    }
}

// Bridge to the parallel `ipc_payloads::ReviewRiskLevel`
// enum (wire-form, serde-enabled). The two enums exist for historical
// reasons (`ipc_dto` is the older shape, `ipc_payloads` is the
// kebab-case serde version); both carry the same four levels.
impl From<RiskLevel> for nrr_shared::ipc_payloads::ReviewRiskLevel {
    fn from(level: RiskLevel) -> Self {
        match level {
            RiskLevel::Low => Self::Low,
            RiskLevel::Medium => Self::Medium,
            RiskLevel::High => Self::High,
            RiskLevel::Critical => Self::Critical,
        }
    }
}

// ── IntegrityStatus ───────────────────────────────────────────────────────────

/// Integrity verification state of a `PolicyRevision`.
///
/// The service computes a SHA-256 hash over policy-content fields when a
/// revision is created and stores it separately from the content. On each
/// load, the service recomputes and compares. A mismatch indicates unexpected
/// mutation of service-owned state (tampering or storage corruption).
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum IntegrityStatus {
    /// Hash has not yet been verified against content. Initial state after
    /// creating a revision in memory before the first persist-and-verify cycle.
    Unverified,
    /// Recomputed hash matches the stored `ContentHash`. Content is intact.
    Verified,
    /// Recomputed hash does not match the stored `ContentHash`. Service-owned
    /// state was mutated outside approved product flows. A `TamperAlert`
    /// `AuditEvent` must be emitted and the user must be notified.
    Tampered,
}

// ── RevisionDiffSummary ───────────────────────────────────────────────────────

/// High-level summary of what changed between two consecutive revisions.
///
/// Attached to a `PolicyRevision` when a previous revision exists to compare
/// against. `None` on the very first revision (no predecessor).
///
/// # Scope
///
/// This struct carries boolean flags and counts suitable for the review UI
/// and risk assessment. Detailed per-rule diffs (added/removed/modified rule
/// identities) are out of scope for this struct — that belongs to a dedicated
/// diff view in the review flow.
///
/// # Full criteria
///
/// This struct is the structural baseline for the full diff metadata model;
/// the service populates it.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct RevisionDiffSummary {
    /// At least one route binding (primary or secondary adapter) changed.
    pub changed_interface_bindings: bool,
    /// The default routing behavior mode changed.
    pub changed_default_behavior: bool,
    /// At least one rule was added, removed, or modified across either rule set.
    pub changed_rules: bool,
    /// Number of rules added across both rule sets.
    pub rules_added: u32,
    /// Number of rules removed across both rule sets.
    pub rules_removed: u32,
    /// Number of rules modified (match value, app match, enabled state, or
    /// comment changed) across both rule sets.
    pub rules_modified: u32,
}

impl RevisionDiffSummary {
    /// Returns `true` when this diff contains no changes at all.
    ///
    /// A no-op diff can occur if a re-import produces the same canonical
    /// content as the active revision. The service should skip creating a new
    /// revision in this case, but this helper guards against accidents.
    pub fn is_empty(&self) -> bool {
        !self.changed_interface_bindings
            && !self.changed_default_behavior
            && !self.changed_rules
            && self.rules_added == 0
            && self.rules_removed == 0
            && self.rules_modified == 0
    }
}

// ── PolicyRevision ────────────────────────────────────────────────────────────

/// An immutable snapshot of a validated routing policy at a point in time.
///
/// `PolicyRevision` is the core record of the revision system. Once created,
/// its policy-content fields must never be mutated — a new revision must be
/// created instead. The `integrity_status` field may be updated by the service
/// after verification.
///
/// # Identity
///
/// Each revision has a unique `id` (prefixed UUID) and a monotonic `seq`.
/// The `seq` counter is shared across all revisions including rejected
/// candidates, allowing detection of gaps in the audit log.
///
/// # Immutability invariant
///
/// Fields covered by `content_hash` (`content`) must not change after the
/// hash is computed. The service enforces this by treating deserialized
/// revisions as immutable value objects and rebuilding the entire revision
/// when content needs to change.
///
/// # Persistence
///
/// `PolicyRevision` is a pure domain type. Persistence, loading, and SHA-256
/// computation are implemented by the service layer.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct PolicyRevision {
    /// Unique identifier for this revision.
    pub id: RevisionId,
    /// Monotonic sequence number. Assigned at creation time.
    pub seq: RevisionSeq,
    /// UTC timestamp when this revision was created.
    pub created_at: UnixTimestamp,
    /// How this revision was created (direct edit, file sync, or import).
    pub source: RevisionSource,
    /// Who initiated the action that created this revision.
    pub actor: RevisionActor,
    /// Normalized, validated policy content. The `content_hash` covers these fields.
    pub content: CanonicalProfile,
    /// SHA-256 fingerprint of `content`. Stored separately to enable integrity
    /// verification without re-parsing the full content.
    pub content_hash: ContentHash,
    /// Summary of changes relative to the immediately preceding revision.
    /// `None` for the first revision (no predecessor to diff against).
    pub diff_summary: Option<RevisionDiffSummary>,
    /// Risk classification assigned by the service at creation time.
    pub risk_level: RiskLevel,
    /// Whether the stored `content_hash` has been verified against `content`.
    pub integrity_status: IntegrityStatus,
}

// ── PendingRevision ───────────────────────────────────────────────────────────

/// A candidate revision awaiting explicit user review and confirmation.
///
/// `PendingRevision` is created when a non-interactive or high-risk change
/// arrives (import, linked-file update, high-risk bulk change). It must be
/// explicitly approved by the user before the service may activate it.
///
/// # Supersession (variant A)
///
/// If a new import arrives while a `PendingRevision` is already waiting,
/// the old candidate is silently displaced. The service records the
/// displacement in the audit log (`AuditEventKind::PendingSuperseded`) and
/// replaces the pending slot with the new candidate. Only one pending revision
/// exists at a time in the Free edition.
///
/// # Activation path
///
/// `Pending` → (user approves) → `Active` via `ActiveRevision`.
/// `Pending` → (user rejects / new import arrives) → displaced; candidate
///   is retained in history but never activated.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct PendingRevision {
    /// The candidate revision awaiting confirmation.
    pub candidate: PolicyRevision,
    /// UTC timestamp when this revision entered the pending state.
    pub queued_at: UnixTimestamp,
    /// ID of the previously pending revision that was displaced when this one
    /// was queued (variant A). `None` if no pending revision existed before.
    pub displaced_revision_id: Option<RevisionId>,
}

// ── ActiveRevision ────────────────────────────────────────────────────────────

/// The currently applied policy revision.
///
/// Only the background service may transition a revision to `Active`. The GUI
/// may request activation (approve pending) but the service is the sole
/// authority that writes routing policy to the system.
///
/// # State machine position
///
/// `Active` revisions are superseded (not deleted) when a new revision is
/// activated. The superseded revision remains in history and is eligible as
/// a rollback target.
///
/// # Rollback
///
/// Rolling back to `LastKnownGoodRevision` creates a new `Active` revision
/// (a copy of the last-known-good content with a new `RevisionId` and `seq`),
/// rather than reactivating the old revision object in place. This preserves
/// the append-only audit history.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct ActiveRevision {
    /// The currently applied revision.
    pub revision: PolicyRevision,
    /// UTC timestamp when this revision became active.
    pub activated_at: UnixTimestamp,
}

// ── LastKnownGoodRevision ─────────────────────────────────────────────────────

/// The last revision that successfully completed the full review-and-confirm
/// flow, regardless of subsequent network or service status.
///
/// `LastKnownGoodRevision` is updated every time a revision is successfully
/// activated (user-confirmed or narrow-approved direct edit). It is the
/// rollback target when the service detects a problem with the current active
/// revision or the user requests a safe rollback.
///
/// # Update rule
///
/// The service sets `LastKnownGoodRevision` ← current `ActiveRevision` each
/// time a new revision is successfully activated. The service may
/// optionally require a "verified applied" signal (e.g. routing table confirmed
/// updated) before promoting to last-known-good.
///
/// # Rollback semantics
///
/// Rollback to last-known-good creates a NEW revision (new `id` + `seq`) with
/// `source = DirectEdit`, `actor = Service`, and content cloned from
/// `last_known_good.revision.content`. This preserves append-only history and
/// produces a full audit trail of the rollback action.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct LastKnownGoodRevision {
    /// The last confirmed-good revision.
    pub revision: PolicyRevision,
    /// UTC timestamp when this revision was confirmed as "good".
    pub confirmed_at: UnixTimestamp,
}

// ── AuditEvent ────────────────────────────────────────────────────────────────

/// Unique identifier for an audit event.
///
/// Format: `"evt-{uuid_v4}"`. Same prefix convention as [`RevisionId`] but
/// with the `evt-` prefix to distinguish event IDs from revision IDs in logs.
#[derive(Clone, Debug, PartialEq, Eq, Hash)]
pub struct AuditEventId(String);

impl AuditEventId {
    const PREFIX: &'static str = "evt-";

    /// Constructs an `AuditEventId` from a pre-formatted prefixed string.
    pub fn from_prefixed_string(id: String) -> Result<Self, &'static str> {
        let suffix = id
            .strip_prefix(Self::PREFIX)
            .ok_or("audit event id must start with \"evt-\"")?;
        if suffix.is_empty() {
            return Err("audit event id suffix must not be empty");
        }
        Ok(Self(id))
    }

    /// Returns the full identifier string.
    pub fn as_str(&self) -> &str {
        &self.0
    }
}

impl fmt::Display for AuditEventId {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(&self.0)
    }
}

/// Why a pending revision was rejected.
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum RejectionReason {
    /// The user explicitly dismissed the pending revision in the review UI.
    UserRejected,
    /// Validation of the candidate content failed (e.g. re-validation after
    /// adapter snapshot changed).
    ValidationFailed,
    /// Integrity check on the candidate revision failed before activation.
    IntegrityCheckFailed,
    /// The pending revision was displaced by a newer import before the user
    /// reviewed it (supersession, variant A).
    SupersededByNewerImport,
}

/// The kind of a recorded audit event.
///
/// Each variant captures the minimum data needed to reconstruct what happened
/// without requiring access to the full revision store.
///
/// # Transitions that MUST generate an `AuditEvent`
///
/// All security-relevant state transitions must produce an audit event:
/// `Import`, `Approval`, `Activation`, `Rejection`, `Rollback`,
/// `TamperAlert`, `IntegrityFailure`, `PendingSuperseded`.
///
/// # Transitions that generate only operational log entries
///
/// Routine, non-security events that do not change policy state: periodic
/// integrity checks that pass, service health pings, GUI snapshot refreshes.
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum AuditEventKind {
    /// A new configuration was imported from an external source and entered
    /// the pending queue. Generated when `PendingRevision` is created.
    Import {
        /// The artifact that was imported.
        artifact: ImportedArtifact,
        /// The sequence number assigned to the new pending revision.
        candidate_seq: RevisionSeq,
    },
    /// The user approved a pending revision for activation.
    Approval {
        /// ID of the revision that was approved.
        approved_revision_id: RevisionId,
        /// ID of the revision that was active before this approval, if any.
        previous_revision_id: Option<RevisionId>,
    },
    /// A revision became the active revision.
    ///
    /// Generated after every successful activation, including direct GUI edits
    /// that skip the pending queue (narrow immediate-apply paths).
    Activation {
        /// ID of the revision that was activated.
        revision_id: RevisionId,
    },
    /// A pending revision was rejected without activation.
    Rejection {
        /// ID of the revision that was rejected.
        revision_id: RevisionId,
        /// Reason for rejection.
        reason: RejectionReason,
    },
    /// A rollback to a previous revision was performed.
    ///
    /// Rollback creates a NEW revision (new `id`/`seq`) rather than
    /// reactivating the old revision object in place.
    Rollback {
        /// ID of the revision that was active before the rollback.
        from_revision_id: RevisionId,
        /// ID of the new revision created to represent the rolled-back content.
        to_revision_id: RevisionId,
    },
    /// Service-owned state was found to be inconsistent: the recomputed
    /// SHA-256 hash of a revision's content did not match the stored hash.
    TamperAlert {
        /// ID of the revision whose integrity check failed.
        revision_id: RevisionId,
        /// The hash recomputed from the current content.
        detected_hash: ContentHash,
        /// The hash stored at creation time.
        stored_hash: ContentHash,
    },
    /// An integrity verification operation failed in a way that prevented
    /// comparison (e.g. hash storage corrupted, revision record unreadable).
    IntegrityFailure {
        /// Human-readable description of the failure mode.
        detail: String,
    },
    /// A pending revision was displaced by a newer import before the user
    /// reviewed it (supersession, variant A — Free edition single-pending slot).
    PendingSuperseded {
        /// ID of the pending revision that was displaced.
        old_revision_id: RevisionId,
        /// Sequence number of the new pending revision that took its place.
        new_candidate_seq: RevisionSeq,
    },
}

/// An immutable, append-only audit record.
///
/// Audit events are written by the service and must never be modified or
/// deleted. The full history of audit events constitutes the audit trail for
/// all policy-affecting actions.
///
/// # Ordering
///
/// Events are ordered by `timestamp`. The service must assign timestamps
/// monotonically (or at least non-decreasingly). Consumers should use
/// `seq`-based ordering when timestamps collide.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct AuditEvent {
    /// Unique identifier for this event.
    pub id: AuditEventId,
    /// UTC timestamp when the event was recorded.
    pub timestamp: UnixTimestamp,
    /// The revision associated with this event, if applicable.
    /// `None` for events not tied to a specific revision (e.g. `IntegrityFailure`
    /// when the revision record itself is unreadable).
    pub revision_id: Option<RevisionId>,
    /// Who initiated the action.
    pub actor: RevisionActor,
    /// The specific event that occurred.
    pub kind: AuditEventKind,
}

// ── RevisionState & state machine ────────────────────────────────────────────

/// Lifecycle state of a `PolicyRevision`.
///
/// Every revision starts as either `Pending` (non-interactive or high-risk
/// origin) or transitions directly to `Active` (narrow immediate-apply paths
/// for direct GUI edits). Terminal states (`Superseded`, `Rejected`,
/// `RolledBack`) are permanent — revisions in these states are never
/// reactivated.
///
/// # Valid transitions
///
/// ```text
/// Pending ──(approved)──────────────────► Active
/// Pending ──(rejected/superseded)───────► Rejected
/// Active  ──(new revision activated)────► Superseded
/// Active  ──(rollback initiated)─────────► RolledBack
/// ```
///
/// All other transitions are invalid. Terminal states have no outgoing edges.
/// Rollback creates a NEW `Active` revision rather than restoring a previous
/// revision to `Active`, preserving the append-only history.
///
/// # Audit events
///
/// Every state transition MUST generate an `AuditEvent`:
/// - `Pending → Active`: `Approval` + `Activation`
/// - `Pending → Rejected`: `Rejection` (with `RejectionReason`)
/// - `Active → Superseded`: `Activation` (of the new revision)
/// - `Active → RolledBack`: `Rollback`
///
/// Operational log entries only (no `AuditEvent`): periodic integrity checks
/// that pass, service health pings, GUI snapshot refreshes.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum RevisionState {
    /// Awaiting explicit user review and confirmation.
    Pending,
    /// Currently applied routing policy.
    Active,
    /// Was active; superseded by a newer revision. Retained in history.
    Superseded,
    /// Was pending; rejected by the user or displaced by a newer import.
    /// Never activated. Retained in history.
    Rejected,
    /// Was active; rolled back. The content was re-applied in a new revision.
    /// Retained in history for auditability.
    RolledBack,
}

impl RevisionState {
    /// Returns `true` when this state can transition to `next`.
    ///
    /// Use this to validate a transition before recording an `AuditEvent` or
    /// updating persistent storage. An invalid transition indicates a
    /// programming error in the caller — the service should log it as an
    /// integrity anomaly and abort the operation.
    pub const fn can_transition_to(self, next: RevisionState) -> bool {
        matches!(
            (self, next),
            (RevisionState::Pending, RevisionState::Active)
                | (RevisionState::Pending, RevisionState::Rejected)
                | (RevisionState::Active, RevisionState::Superseded)
                | (RevisionState::Active, RevisionState::RolledBack)
        )
    }

    /// Returns `true` if this is a terminal state (no outgoing transitions).
    pub const fn is_terminal(self) -> bool {
        matches!(
            self,
            RevisionState::Superseded | RevisionState::Rejected | RevisionState::RolledBack
        )
    }
}

// ── RollbackOutcome ───────────────────────────────────────────────────────────

/// Why a rollback attempt was blocked before any state change occurred.
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum RollbackBlockedReason {
    /// There is no `LastKnownGoodRevision` to roll back to. This can happen
    /// on the first-ever activation before any revision has been confirmed good,
    /// or if the last-known-good record was lost.
    NoLastKnownGood,
    /// The last-known-good revision is already the active revision. There is
    /// nothing to roll back to.
    LastKnownGoodIsAlreadyActive,
    /// The `LastKnownGoodRevision` failed its integrity check before the
    /// service could apply it. Rolling back to a potentially tampered revision
    /// is refused until the user explicitly overrides.
    IntegrityCheckFailed,
}

/// Outcome of a rollback-to-last-known-good operation.
///
/// Rollback is an atomic service operation that:
/// 1. Verifies the `LastKnownGoodRevision` passes an integrity check.
/// 2. Creates a **new** `PolicyRevision` (new `id` + `seq`) whose `content`
///    clones the last-known-good content.  `source = DirectEdit`,
///    `actor = Service`.
/// 3. Transitions the current `ActiveRevision` to `RolledBack`.
/// 4. Activates the new revision.
/// 5. Emits a `Rollback` `AuditEvent`.
///
/// On `Blocked`, no state change is made and no `AuditEvent` is emitted.
/// An operational log entry is written explaining the block reason.
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum RollbackOutcome {
    /// Rollback completed. A new revision was created and activated.
    Success {
        /// The new revision's identifier (cloned content, new identity).
        new_revision_id: RevisionId,
        /// The new revision's sequence number.
        new_seq: RevisionSeq,
    },
    /// Rollback was refused before any state change occurred.
    Blocked(RollbackBlockedReason),
}

// ── Tests ─────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    // ── RevisionId ────────────────────────────────────────────────────────────

    #[test]
    fn revision_id_accepts_valid_prefixed_string() {
        let id = RevisionId::from_prefixed_string(
            "rev-550e8400-e29b-41d4-a716-446655440000".to_string(),
        );
        assert!(id.is_ok());
        let id = id.unwrap_or_else(|e| panic!("expected Ok: {e}"));
        assert_eq!(id.as_str(), "rev-550e8400-e29b-41d4-a716-446655440000");
        assert_eq!(id.uuid_part(), "550e8400-e29b-41d4-a716-446655440000");
    }

    #[test]
    fn revision_id_rejects_missing_prefix() {
        assert!(RevisionId::from_prefixed_string(
            "550e8400-e29b-41d4-a716-446655440000".to_string()
        )
        .is_err());
    }

    #[test]
    fn revision_id_rejects_prefix_only() {
        assert!(RevisionId::from_prefixed_string("rev-".to_string()).is_err());
    }

    #[test]
    fn revision_id_display_equals_full_string() {
        let id = RevisionId::from_prefixed_string("rev-abc-123".to_string())
            .unwrap_or_else(|e| panic!("expected Ok: {e}"));
        assert_eq!(id.to_string(), "rev-abc-123");
    }

    // ── RevisionSeq ───────────────────────────────────────────────────────────

    #[test]
    fn revision_seq_first_is_one() {
        assert_eq!(RevisionSeq::FIRST.value(), 1);
    }

    #[test]
    fn revision_seq_rejects_zero() {
        assert!(RevisionSeq::new(0).is_err());
    }

    #[test]
    fn revision_seq_next_increments_by_one() {
        let seq = RevisionSeq::FIRST;
        let next = seq.next().unwrap_or_else(|| panic!("overflow on seq 1"));
        assert_eq!(next.value(), 2);
        assert!(next > seq);
    }

    #[test]
    fn revision_seq_ordering_is_monotonic() {
        let a = RevisionSeq::new(1).unwrap_or_else(|e| panic!("{e}"));
        let b = RevisionSeq::new(5).unwrap_or_else(|e| panic!("{e}"));
        let c = RevisionSeq::new(5).unwrap_or_else(|e| panic!("{e}"));
        assert!(a < b);
        assert_eq!(b, c);
    }

    // ── ContentHash ───────────────────────────────────────────────────────────

    #[test]
    fn content_hash_roundtrip_via_hex() {
        let bytes = [0xabu8; 32];
        let hash = ContentHash::from_bytes(bytes);
        let hex = hash.to_hex_string();
        assert_eq!(hex.len(), 64);
        assert!(hex.chars().all(|c| c.is_ascii_hexdigit()));
        let parsed = ContentHash::from_hex_string(&hex)
            .unwrap_or_else(|e| panic!("hex roundtrip failed: {e}"));
        assert_eq!(hash, parsed);
    }

    #[test]
    fn content_hash_rejects_wrong_length() {
        assert!(ContentHash::from_hex_string("ab").is_err());
        assert!(ContentHash::from_hex_string(&"ab".repeat(33)).is_err());
    }

    #[test]
    fn content_hash_rejects_invalid_hex_chars() {
        let invalid = "zz".repeat(32);
        assert!(ContentHash::from_hex_string(&invalid).is_err());
    }

    #[test]
    fn content_hash_accepts_uppercase_hex() {
        let upper = "AB".repeat(32);
        assert!(ContentHash::from_hex_string(&upper).is_ok());
    }

    #[test]
    fn content_hash_all_zeros_is_valid() {
        let hash = ContentHash::from_bytes([0u8; 32]);
        assert_eq!(hash.to_hex_string(), "0".repeat(64));
    }

    // ── UnixTimestamp ─────────────────────────────────────────────────────────

    #[test]
    fn unix_timestamp_roundtrips() {
        let ts = UnixTimestamp::from_secs(1_700_000_000);
        assert_eq!(ts.as_secs(), 1_700_000_000);
        assert_eq!(ts.to_string(), "1700000000");
    }

    #[test]
    fn unix_timestamp_ordering_is_chronological() {
        let earlier = UnixTimestamp::from_secs(100);
        let later = UnixTimestamp::from_secs(200);
        assert!(earlier < later);
    }

    // ── ImportedArtifact ──────────────────────────────────────────────────────

    #[test]
    fn imported_artifact_snapshot_channel_is_default_mode() {
        let artifact = ImportedArtifact {
            source_path: "C:/Users/user/Downloads/preset.yaml".to_string(),
            file_hash: ContentHash::from_bytes([0x01u8; 32]),
            imported_at: UnixTimestamp::from_secs(1_700_000_000),
            channel: ImportChannel::Snapshot,
        };
        assert_eq!(artifact.channel, ImportChannel::Snapshot);
        assert!(!artifact.source_path.is_empty());
    }

    #[test]
    fn linked_channel_is_reserved_and_distinct_from_snapshot() {
        assert_ne!(ImportChannel::Snapshot, ImportChannel::Linked);
    }

    // ── CanonicalProfile linkage ───────────────────────────────────────────────
    //
    // CanonicalProfile is defined in crate::canonical and imported
    // here via `pub use`. This test verifies that the type is accessible from
    // the revision module and can be constructed, which confirms the import path.

    #[test]
    fn canonical_profile_is_accessible_from_revision_module() {
        use crate::{canonical::CanonicalRuleBook, AdapterIdentity, RouteBinding};
        use nrr_shared::{BindingSource, RouteBehaviorMode, RouteRole};

        let profile = CanonicalProfile {
            primary: RouteBinding {
                role: RouteRole::Primary,
                adapter: AdapterIdentity {
                    stable_id: "eth0".to_string(),
                    display_name: "Ethernet".to_string(),
                },
                source: BindingSource::UserAssigned,
            },
            secondary: None,
            behavior_mode: RouteBehaviorMode::PreferPrimary,
            rule_book: CanonicalRuleBook::default(),
        };
        assert!(profile.secondary.is_none());
        assert_eq!(profile.primary.adapter.stable_id, "eth0");
    }

    // ── RiskLevel ─────────────────────────────────────────────────────────────

    #[test]
    fn risk_level_ordering_low_lt_medium_lt_high() {
        assert!(RiskLevel::Low < RiskLevel::Medium);
        assert!(RiskLevel::Medium < RiskLevel::High);
        assert!(RiskLevel::Low < RiskLevel::High);
    }

    #[test]
    fn risk_level_display_is_lowercase_slug() {
        assert_eq!(RiskLevel::Low.to_string(), "low");
        assert_eq!(RiskLevel::Medium.to_string(), "medium");
        assert_eq!(RiskLevel::High.to_string(), "high");
    }

    #[test]
    fn risk_level_equality_is_reflexive() {
        assert_eq!(RiskLevel::High, RiskLevel::High);
        assert_ne!(RiskLevel::Low, RiskLevel::High);
    }

    // ── IntegrityStatus ───────────────────────────────────────────────────────

    #[test]
    fn integrity_status_variants_are_distinct() {
        assert_ne!(IntegrityStatus::Unverified, IntegrityStatus::Verified);
        assert_ne!(IntegrityStatus::Verified, IntegrityStatus::Tampered);
        assert_ne!(IntegrityStatus::Unverified, IntegrityStatus::Tampered);
    }

    // ── RevisionDiffSummary ───────────────────────────────────────────────────

    #[test]
    fn revision_diff_summary_is_empty_when_all_zero() {
        let diff = RevisionDiffSummary {
            changed_interface_bindings: false,
            changed_default_behavior: false,
            changed_rules: false,
            rules_added: 0,
            rules_removed: 0,
            rules_modified: 0,
        };
        assert!(diff.is_empty());
    }

    #[test]
    fn revision_diff_summary_not_empty_when_binding_changed() {
        let diff = RevisionDiffSummary {
            changed_interface_bindings: true,
            changed_default_behavior: false,
            changed_rules: false,
            rules_added: 0,
            rules_removed: 0,
            rules_modified: 0,
        };
        assert!(!diff.is_empty());
    }

    #[test]
    fn revision_diff_summary_not_empty_when_rules_added() {
        let diff = RevisionDiffSummary {
            changed_interface_bindings: false,
            changed_default_behavior: false,
            changed_rules: true,
            rules_added: 3,
            rules_removed: 0,
            rules_modified: 0,
        };
        assert!(!diff.is_empty());
    }

    // ── RevisionSource ────────────────────────────────────────────────────────

    #[test]
    fn revision_source_import_carries_artifact() {
        let artifact = ImportedArtifact {
            source_path: "preset.yaml".to_string(),
            file_hash: ContentHash::from_bytes([0xffu8; 32]),
            imported_at: UnixTimestamp::from_secs(1_700_000_000),
            channel: ImportChannel::Snapshot,
        };
        let source = RevisionSource::Import(artifact.clone());
        match source {
            RevisionSource::Import(a) => assert_eq!(a.source_path, "preset.yaml"),
            _ => panic!("expected Import variant"),
        }
    }

    #[test]
    fn revision_source_direct_edit_and_file_sync_are_distinct() {
        assert_ne!(RevisionSource::DirectEdit, RevisionSource::FileSync);
    }

    // ── RevisionActor ─────────────────────────────────────────────────────────

    #[test]
    fn revision_actor_variants_are_distinct() {
        assert_ne!(RevisionActor::LocalUser, RevisionActor::Service);
    }

    // ── AuditEventId ─────────────────────────────────────────────────────────

    #[test]
    fn audit_event_id_accepts_valid_prefixed_string() {
        let id = AuditEventId::from_prefixed_string(
            "evt-550e8400-e29b-41d4-a716-446655440000".to_string(),
        );
        assert!(id.is_ok());
        let id = id.unwrap_or_else(|e| panic!("expected Ok: {e}"));
        assert_eq!(id.as_str(), "evt-550e8400-e29b-41d4-a716-446655440000");
        assert_eq!(id.to_string(), "evt-550e8400-e29b-41d4-a716-446655440000");
    }

    #[test]
    fn audit_event_id_rejects_missing_prefix() {
        assert!(AuditEventId::from_prefixed_string("some-id".to_string()).is_err());
    }

    #[test]
    fn audit_event_id_rejects_prefix_only() {
        assert!(AuditEventId::from_prefixed_string("evt-".to_string()).is_err());
    }

    // ── PolicyRevision ────────────────────────────────────────────────────────

    fn make_test_profile() -> CanonicalProfile {
        use crate::{canonical::CanonicalRuleBook, AdapterIdentity, RouteBinding};
        use nrr_shared::{BindingSource, RouteBehaviorMode, RouteRole};
        CanonicalProfile {
            primary: RouteBinding {
                role: RouteRole::Primary,
                adapter: AdapterIdentity {
                    stable_id: "eth0".to_string(),
                    display_name: "Ethernet".to_string(),
                },
                source: BindingSource::UserAssigned,
            },
            secondary: None,
            behavior_mode: RouteBehaviorMode::PreferPrimary,
            rule_book: CanonicalRuleBook::default(),
        }
    }

    fn make_test_revision(id: &str, seq: u64) -> PolicyRevision {
        PolicyRevision {
            id: RevisionId::from_prefixed_string(id.to_string()).unwrap_or_else(|e| panic!("{e}")),
            seq: RevisionSeq::new(seq).unwrap_or_else(|e| panic!("{e}")),
            created_at: UnixTimestamp::from_secs(1_700_000_000 + seq),
            source: RevisionSource::DirectEdit,
            actor: RevisionActor::LocalUser,
            content: make_test_profile(),
            content_hash: ContentHash::from_bytes([seq as u8; 32]),
            diff_summary: None,
            risk_level: RiskLevel::Low,
            integrity_status: IntegrityStatus::Unverified,
        }
    }

    #[test]
    fn policy_revision_fields_are_accessible() {
        let rev = make_test_revision("rev-abc-001", 1);
        assert_eq!(rev.id.as_str(), "rev-abc-001");
        assert_eq!(rev.seq.value(), 1);
        assert_eq!(rev.risk_level, RiskLevel::Low);
        assert_eq!(rev.integrity_status, IntegrityStatus::Unverified);
        assert_eq!(rev.actor, RevisionActor::LocalUser);
        assert!(rev.diff_summary.is_none());
    }

    #[test]
    fn policy_revision_with_diff_summary() {
        let mut rev = make_test_revision("rev-abc-002", 2);
        rev.diff_summary = Some(RevisionDiffSummary {
            changed_interface_bindings: false,
            changed_default_behavior: false,
            changed_rules: true,
            rules_added: 1,
            rules_removed: 0,
            rules_modified: 0,
        });
        let diff = rev
            .diff_summary
            .as_ref()
            .unwrap_or_else(|| panic!("expected Some"));
        assert!(!diff.is_empty());
        assert_eq!(diff.rules_added, 1);
    }

    // ── PendingRevision ───────────────────────────────────────────────────────

    #[test]
    fn pending_revision_no_displaced_id_when_first_pending() {
        let pending = PendingRevision {
            candidate: make_test_revision("rev-p-001", 1),
            queued_at: UnixTimestamp::from_secs(1_700_000_100),
            displaced_revision_id: None,
        };
        assert!(pending.displaced_revision_id.is_none());
        assert_eq!(pending.candidate.seq.value(), 1);
    }

    #[test]
    fn pending_revision_records_displaced_id_on_supersession() {
        let old_id = RevisionId::from_prefixed_string("rev-old-001".to_string())
            .unwrap_or_else(|e| panic!("{e}"));
        let pending = PendingRevision {
            candidate: make_test_revision("rev-new-002", 2),
            queued_at: UnixTimestamp::from_secs(1_700_000_200),
            displaced_revision_id: Some(old_id.clone()),
        };
        let displaced = pending
            .displaced_revision_id
            .as_ref()
            .unwrap_or_else(|| panic!("expected Some"));
        assert_eq!(displaced.as_str(), "rev-old-001");
    }

    // ── ActiveRevision ────────────────────────────────────────────────────────

    #[test]
    fn active_revision_wraps_policy_revision_with_activation_time() {
        let rev = make_test_revision("rev-act-001", 1);
        let activated_at = UnixTimestamp::from_secs(1_700_001_000);
        let active = ActiveRevision {
            revision: rev.clone(),
            activated_at,
        };
        assert_eq!(active.revision.id.as_str(), "rev-act-001");
        assert_eq!(active.activated_at.as_secs(), 1_700_001_000);
    }

    // ── LastKnownGoodRevision ─────────────────────────────────────────────────

    #[test]
    fn last_known_good_wraps_revision_with_confirmation_time() {
        let rev = make_test_revision("rev-lkg-001", 1);
        let confirmed_at = UnixTimestamp::from_secs(1_700_002_000);
        let lkg = LastKnownGoodRevision {
            revision: rev.clone(),
            confirmed_at,
        };
        assert_eq!(lkg.revision.seq.value(), 1);
        assert_eq!(lkg.confirmed_at.as_secs(), 1_700_002_000);
    }

    // ── AuditEvent / AuditEventKind ───────────────────────────────────────────

    #[test]
    fn audit_event_activation_kind_carries_revision_id() {
        let rev_id = RevisionId::from_prefixed_string("rev-act-007".to_string())
            .unwrap_or_else(|e| panic!("{e}"));
        let kind = AuditEventKind::Activation {
            revision_id: rev_id.clone(),
        };
        match kind {
            AuditEventKind::Activation { revision_id } => {
                assert_eq!(revision_id.as_str(), "rev-act-007");
            }
            _ => panic!("expected Activation variant"),
        }
    }

    #[test]
    fn audit_event_rejection_carries_reason() {
        let rev_id = RevisionId::from_prefixed_string("rev-rej-001".to_string())
            .unwrap_or_else(|e| panic!("{e}"));
        let kind = AuditEventKind::Rejection {
            revision_id: rev_id,
            reason: RejectionReason::UserRejected,
        };
        match kind {
            AuditEventKind::Rejection { reason, .. } => {
                assert_eq!(reason, RejectionReason::UserRejected);
            }
            _ => panic!("expected Rejection variant"),
        }
    }

    #[test]
    fn audit_event_rollback_records_both_revision_ids() {
        let from = RevisionId::from_prefixed_string("rev-from-001".to_string())
            .unwrap_or_else(|e| panic!("{e}"));
        let to = RevisionId::from_prefixed_string("rev-to-002".to_string())
            .unwrap_or_else(|e| panic!("{e}"));
        let kind = AuditEventKind::Rollback {
            from_revision_id: from,
            to_revision_id: to,
        };
        match kind {
            AuditEventKind::Rollback {
                from_revision_id,
                to_revision_id,
            } => {
                assert_eq!(from_revision_id.as_str(), "rev-from-001");
                assert_eq!(to_revision_id.as_str(), "rev-to-002");
            }
            _ => panic!("expected Rollback variant"),
        }
    }

    #[test]
    fn audit_event_pending_superseded_records_both_seqs() {
        let old_id = RevisionId::from_prefixed_string("rev-old-001".to_string())
            .unwrap_or_else(|e| panic!("{e}"));
        let new_seq = RevisionSeq::new(5).unwrap_or_else(|e| panic!("{e}"));
        let kind = AuditEventKind::PendingSuperseded {
            old_revision_id: old_id,
            new_candidate_seq: new_seq,
        };
        match kind {
            AuditEventKind::PendingSuperseded {
                old_revision_id,
                new_candidate_seq,
            } => {
                assert_eq!(old_revision_id.as_str(), "rev-old-001");
                assert_eq!(new_candidate_seq.value(), 5);
            }
            _ => panic!("expected PendingSuperseded variant"),
        }
    }

    #[test]
    fn audit_event_tamper_alert_carries_hash_pair() {
        let rev_id = RevisionId::from_prefixed_string("rev-tamper-001".to_string())
            .unwrap_or_else(|e| panic!("{e}"));
        let stored = ContentHash::from_bytes([0xaau8; 32]);
        let detected = ContentHash::from_bytes([0xbbu8; 32]);
        let kind = AuditEventKind::TamperAlert {
            revision_id: rev_id,
            detected_hash: detected.clone(),
            stored_hash: stored.clone(),
        };
        match kind {
            AuditEventKind::TamperAlert {
                detected_hash,
                stored_hash,
                ..
            } => {
                assert_ne!(detected_hash, stored_hash);
            }
            _ => panic!("expected TamperAlert variant"),
        }
    }

    #[test]
    fn full_audit_event_struct_is_constructible() {
        let event = AuditEvent {
            id: AuditEventId::from_prefixed_string("evt-abc-001".to_string())
                .unwrap_or_else(|e| panic!("{e}")),
            timestamp: UnixTimestamp::from_secs(1_700_000_000),
            revision_id: Some(
                RevisionId::from_prefixed_string("rev-abc-001".to_string())
                    .unwrap_or_else(|e| panic!("{e}")),
            ),
            actor: RevisionActor::LocalUser,
            kind: AuditEventKind::Activation {
                revision_id: RevisionId::from_prefixed_string("rev-abc-001".to_string())
                    .unwrap_or_else(|e| panic!("{e}")),
            },
        };
        assert_eq!(event.id.as_str(), "evt-abc-001");
        assert_eq!(event.actor, RevisionActor::LocalUser);
        assert!(event.revision_id.is_some());
    }

    #[test]
    fn audit_event_integrity_failure_has_no_revision_id() {
        let event = AuditEvent {
            id: AuditEventId::from_prefixed_string("evt-fail-001".to_string())
                .unwrap_or_else(|e| panic!("{e}")),
            timestamp: UnixTimestamp::from_secs(1_700_000_001),
            revision_id: None,
            actor: RevisionActor::Service,
            kind: AuditEventKind::IntegrityFailure {
                detail: "revision record unreadable".to_string(),
            },
        };
        assert!(event.revision_id.is_none());
        assert_eq!(event.actor, RevisionActor::Service);
    }

    // ── State machine ──────────────────────────────────────────────────────────

    #[test]
    fn pending_can_transition_to_active_and_rejected() {
        assert!(RevisionState::Pending.can_transition_to(RevisionState::Active));
        assert!(RevisionState::Pending.can_transition_to(RevisionState::Rejected));
    }

    #[test]
    fn active_can_transition_to_superseded_and_rolled_back() {
        assert!(RevisionState::Active.can_transition_to(RevisionState::Superseded));
        assert!(RevisionState::Active.can_transition_to(RevisionState::RolledBack));
    }

    #[test]
    fn invalid_transitions_are_rejected() {
        // Pending cannot jump to Superseded or RolledBack
        assert!(!RevisionState::Pending.can_transition_to(RevisionState::Superseded));
        assert!(!RevisionState::Pending.can_transition_to(RevisionState::RolledBack));
        // Active cannot go directly to Rejected
        assert!(!RevisionState::Active.can_transition_to(RevisionState::Rejected));
        // Active cannot transition to itself
        assert!(!RevisionState::Active.can_transition_to(RevisionState::Active));
        // Pending cannot transition to itself
        assert!(!RevisionState::Pending.can_transition_to(RevisionState::Pending));
    }

    #[test]
    fn terminal_states_have_no_valid_transitions() {
        let terminals = [
            RevisionState::Superseded,
            RevisionState::Rejected,
            RevisionState::RolledBack,
        ];
        let all_states = [
            RevisionState::Pending,
            RevisionState::Active,
            RevisionState::Superseded,
            RevisionState::Rejected,
            RevisionState::RolledBack,
        ];
        for terminal in terminals {
            assert!(terminal.is_terminal(), "{terminal:?} should be terminal");
            for next in all_states {
                assert!(
                    !terminal.can_transition_to(next),
                    "{terminal:?} → {next:?} must be invalid"
                );
            }
        }
    }

    #[test]
    fn non_terminal_states_are_pending_and_active() {
        assert!(!RevisionState::Pending.is_terminal());
        assert!(!RevisionState::Active.is_terminal());
    }

    // ── Rollback outcome model ─────────────────────────────────────────────────

    // Scenario: normal apply flow (Pending → Active)
    #[test]
    fn rollback_success_carries_new_revision_identity() {
        let outcome = RollbackOutcome::Success {
            new_revision_id: RevisionId::from_prefixed_string("rev-rollback-001".to_string())
                .unwrap_or_else(|e| panic!("{e}")),
            new_seq: RevisionSeq::new(5).unwrap_or_else(|e| panic!("{e}")),
        };
        match outcome {
            RollbackOutcome::Success {
                new_revision_id,
                new_seq,
            } => {
                assert_eq!(new_revision_id.as_str(), "rev-rollback-001");
                assert_eq!(new_seq.value(), 5);
            }
            RollbackOutcome::Blocked(_) => panic!("expected Success"),
        }
    }

    // Scenario: rollback blocked — no last known good
    #[test]
    fn rollback_blocked_no_last_known_good() {
        let outcome = RollbackOutcome::Blocked(RollbackBlockedReason::NoLastKnownGood);
        match outcome {
            RollbackOutcome::Blocked(reason) => {
                assert_eq!(reason, RollbackBlockedReason::NoLastKnownGood);
            }
            RollbackOutcome::Success { .. } => panic!("expected Blocked"),
        }
    }

    // Scenario: rollback blocked — last known good is already active
    #[test]
    fn rollback_blocked_already_active() {
        let outcome = RollbackOutcome::Blocked(RollbackBlockedReason::LastKnownGoodIsAlreadyActive);
        assert_eq!(
            outcome,
            RollbackOutcome::Blocked(RollbackBlockedReason::LastKnownGoodIsAlreadyActive)
        );
    }

    // Scenario: rollback blocked — integrity check failed on last known good
    #[test]
    fn rollback_blocked_integrity_check_failed() {
        let outcome = RollbackOutcome::Blocked(RollbackBlockedReason::IntegrityCheckFailed);
        assert_eq!(
            outcome,
            RollbackOutcome::Blocked(RollbackBlockedReason::IntegrityCheckFailed)
        );
    }

    // Scenario: new import displaces existing pending (PendingSuperseded audit event)
    #[test]
    fn pending_superseded_audit_event_scenario() {
        let old_id = RevisionId::from_prefixed_string("rev-old-pending-001".to_string())
            .unwrap_or_else(|e| panic!("{e}"));
        let new_seq = RevisionSeq::new(3).unwrap_or_else(|e| panic!("{e}"));
        // Old pending transitions to Rejected (with SupersededByNewerImport reason)
        assert!(RevisionState::Pending.can_transition_to(RevisionState::Rejected));
        // Audit event type is PendingSuperseded
        let kind = AuditEventKind::PendingSuperseded {
            old_revision_id: old_id,
            new_candidate_seq: new_seq,
        };
        match kind {
            AuditEventKind::PendingSuperseded {
                new_candidate_seq, ..
            } => {
                assert_eq!(new_candidate_seq.value(), 3);
            }
            _ => panic!("expected PendingSuperseded"),
        }
    }

    // Scenario: integrity check failure on active revision triggers TamperAlert
    #[test]
    fn integrity_failure_scenario_tamper_alert() {
        let rev_id = RevisionId::from_prefixed_string("rev-tampered-001".to_string())
            .unwrap_or_else(|e| panic!("{e}"));
        let stored = ContentHash::from_bytes([0x01u8; 32]);
        let detected = ContentHash::from_bytes([0x02u8; 32]);
        // Hashes differ → TamperAlert event
        assert_ne!(stored, detected);
        let event = AuditEvent {
            id: AuditEventId::from_prefixed_string("evt-tamper-001".to_string())
                .unwrap_or_else(|e| panic!("{e}")),
            timestamp: UnixTimestamp::from_secs(1_700_000_999),
            revision_id: Some(rev_id.clone()),
            actor: RevisionActor::Service,
            kind: AuditEventKind::TamperAlert {
                revision_id: rev_id,
                detected_hash: detected,
                stored_hash: stored,
            },
        };
        assert_eq!(event.actor, RevisionActor::Service);
        assert!(event.revision_id.is_some());
    }
}
