//! Minimal IP/TCP/UDP header parsing for the fake-IP relay.
//!
//! The relay reads raw IP packets from the TUN adapter and must answer one
//! question per packet before any stack work happens: *which flow is this, and
//! is it the first packet of a new one?* That is all this module does — enough
//! header parsing to build the 5-tuple and spot a TCP SYN, and nothing more.
//!
//! Deliberately not a packet library: it never rewrites, reassembles or
//! validates checksums (the userspace stack does that). Keeping it a pure
//! function over a byte slice is what makes the relay's routing decisions
//! testable without a network — every test below is a hand-built packet.

use std::net::{IpAddr, Ipv4Addr, Ipv6Addr, SocketAddr};

/// Transport protocols the relay handles. Anything else is dropped: fake
/// addresses only ever appear as the destination of a connection the user's
/// application opened by NAME, and names are reached over TCP or UDP.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub enum FlowProtocol {
    Tcp,
    Udp,
}

impl FlowProtocol {
    #[must_use]
    pub fn slug(self) -> &'static str {
        match self {
            Self::Tcp => "tcp",
            Self::Udp => "udp",
        }
    }
}

/// The identity of one flow: protocol plus both endpoints. Two packets of the
/// same conversation produce the same key in each direction of travel, so the
/// relay's session table is keyed on it directly.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct FlowKey {
    pub protocol: FlowProtocol,
    pub source: SocketAddr,
    pub destination: SocketAddr,
}

/// A parsed packet: its flow plus the facts the relay acts on.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct ParsedPacket {
    pub key: FlowKey,
    /// True for a TCP SYN without ACK — the packet that opens a connection and
    /// therefore the one that must create a session.
    pub is_connection_open: bool,
    /// Offset of the transport payload within the packet, so the relay can
    /// forward a UDP datagram's bytes without re-parsing.
    pub payload_offset: usize,
}

const PROTO_TCP: u8 = 6;
const PROTO_UDP: u8 = 17;
const TCP_FLAG_SYN: u8 = 0x02;
const TCP_FLAG_ACK: u8 = 0x10;

/// Parse one IP packet. Returns `None` for anything the relay does not handle:
/// truncated packets, non-IP versions, protocols other than TCP/UDP, IPv6
/// extension-header chains, and IPv4 fragments after the first (a fragmented
/// first packet has no complete transport header to key on).
#[must_use]
pub fn parse_packet(packet: &[u8]) -> Option<ParsedPacket> {
    let version = packet.first()? >> 4;
    match version {
        4 => parse_ipv4(packet),
        6 => parse_ipv6(packet),
        _ => None,
    }
}

fn parse_ipv4(packet: &[u8]) -> Option<ParsedPacket> {
    if packet.len() < 20 {
        return None;
    }
    let header_len = usize::from(packet[0] & 0x0f) * 4;
    if header_len < 20 || packet.len() < header_len {
        return None;
    }
    // Fragment offset non-zero → not the first fragment, so the transport
    // header is not here. The stack reassembles; the relay ignores.
    let fragment_offset = u16::from_be_bytes([packet[6], packet[7]]) & 0x1fff;
    if fragment_offset != 0 {
        return None;
    }
    let protocol = transport_protocol(packet[9])?;
    let source_ip = Ipv4Addr::new(packet[12], packet[13], packet[14], packet[15]);
    let destination_ip = Ipv4Addr::new(packet[16], packet[17], packet[18], packet[19]);
    build(
        packet,
        header_len,
        protocol,
        IpAddr::V4(source_ip),
        IpAddr::V4(destination_ip),
    )
}

fn parse_ipv6(packet: &[u8]) -> Option<ParsedPacket> {
    const HEADER_LEN: usize = 40;
    if packet.len() < HEADER_LEN {
        return None;
    }
    // Only a bare next-header of TCP/UDP is handled; an extension-header chain
    // returns None rather than being walked, because a fake-IP flow never
    // legitimately carries one (it is generated by a local application's own
    // stack towards an address we invented).
    let protocol = transport_protocol(packet[6])?;
    let mut source = [0u8; 16];
    let mut destination = [0u8; 16];
    source.copy_from_slice(&packet[8..24]);
    destination.copy_from_slice(&packet[24..40]);
    build(
        packet,
        HEADER_LEN,
        protocol,
        IpAddr::V6(Ipv6Addr::from(source)),
        IpAddr::V6(Ipv6Addr::from(destination)),
    )
}

fn transport_protocol(value: u8) -> Option<FlowProtocol> {
    match value {
        PROTO_TCP => Some(FlowProtocol::Tcp),
        PROTO_UDP => Some(FlowProtocol::Udp),
        _ => None,
    }
}

fn build(
    packet: &[u8],
    header_len: usize,
    protocol: FlowProtocol,
    source_ip: IpAddr,
    destination_ip: IpAddr,
) -> Option<ParsedPacket> {
    let transport = packet.get(header_len..)?;
    if transport.len() < 8 {
        return None;
    }
    let source_port = u16::from_be_bytes([transport[0], transport[1]]);
    let destination_port = u16::from_be_bytes([transport[2], transport[3]]);
    let (is_connection_open, payload_offset) = match protocol {
        FlowProtocol::Tcp => {
            if transport.len() < 20 {
                return None;
            }
            let data_offset = usize::from(transport[12] >> 4) * 4;
            if data_offset < 20 || transport.len() < data_offset {
                return None;
            }
            let flags = transport[13];
            let opens = (flags & TCP_FLAG_SYN) != 0 && (flags & TCP_FLAG_ACK) == 0;
            (opens, header_len + data_offset)
        }
        // Every UDP datagram to an unseen endpoint opens a flow; the session
        // table decides whether it is actually new.
        FlowProtocol::Udp => (true, header_len + 8),
    };
    Some(ParsedPacket {
        key: FlowKey {
            protocol,
            source: SocketAddr::new(source_ip, source_port),
            destination: SocketAddr::new(destination_ip, destination_port),
        },
        is_connection_open,
        payload_offset,
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Build an IPv4 packet with the given protocol and transport bytes.
    fn ipv4(protocol: u8, transport: &[u8]) -> Vec<u8> {
        let mut packet = vec![0u8; 20];
        packet[0] = 0x45; // version 4, header length 5 words
        let total = 20 + transport.len();
        packet[2..4].copy_from_slice(&(total as u16).to_be_bytes());
        packet[9] = protocol;
        packet[12..16].copy_from_slice(&[10, 0, 0, 2]);
        packet[16..20].copy_from_slice(&[198, 18, 0, 5]);
        packet.extend_from_slice(transport);
        packet
    }

    fn tcp(src_port: u16, dst_port: u16, flags: u8) -> Vec<u8> {
        let mut segment = vec![0u8; 20];
        segment[0..2].copy_from_slice(&src_port.to_be_bytes());
        segment[2..4].copy_from_slice(&dst_port.to_be_bytes());
        segment[12] = 5 << 4; // data offset: 5 words
        segment[13] = flags;
        segment
    }

    fn udp(src_port: u16, dst_port: u16, payload: &[u8]) -> Vec<u8> {
        let mut datagram = vec![0u8; 8];
        datagram[0..2].copy_from_slice(&src_port.to_be_bytes());
        datagram[2..4].copy_from_slice(&dst_port.to_be_bytes());
        datagram.extend_from_slice(payload);
        datagram
    }

    #[test]
    fn tcp_syn_is_recognised_as_opening_a_flow() {
        let packet = ipv4(PROTO_TCP, &tcp(54321, 443, TCP_FLAG_SYN));
        let parsed = parse_packet(&packet).expect("parses");
        assert_eq!(parsed.key.protocol, FlowProtocol::Tcp);
        assert_eq!(parsed.key.source, "10.0.0.2:54321".parse().unwrap());
        assert_eq!(parsed.key.destination, "198.18.0.5:443".parse().unwrap());
        assert!(parsed.is_connection_open);
    }

    #[test]
    fn tcp_syn_ack_and_plain_data_do_not_open_a_flow() {
        let syn_ack = ipv4(PROTO_TCP, &tcp(1, 2, TCP_FLAG_SYN | TCP_FLAG_ACK));
        assert!(!parse_packet(&syn_ack).expect("parses").is_connection_open);
        let data = ipv4(PROTO_TCP, &tcp(1, 2, TCP_FLAG_ACK));
        assert!(!parse_packet(&data).expect("parses").is_connection_open);
    }

    #[test]
    fn udp_payload_offset_points_at_the_datagram_body() {
        let packet = ipv4(PROTO_UDP, &udp(5000, 53, b"query"));
        let parsed = parse_packet(&packet).expect("parses");
        assert_eq!(parsed.key.protocol, FlowProtocol::Udp);
        assert!(parsed.is_connection_open);
        assert_eq!(&packet[parsed.payload_offset..], b"query");
    }

    #[test]
    fn tcp_options_are_skipped_when_locating_the_payload() {
        let mut segment = tcp(1, 2, TCP_FLAG_ACK);
        segment[12] = 6 << 4; // 6 words = 20 header + 4 option bytes
        segment.extend_from_slice(&[1, 1, 1, 0]); // option padding
        segment.extend_from_slice(b"body");
        let packet = ipv4(PROTO_TCP, &segment);
        let parsed = parse_packet(&packet).expect("parses");
        assert_eq!(&packet[parsed.payload_offset..], b"body");
    }

    #[test]
    fn ipv6_tcp_is_parsed() {
        let mut packet = vec![0u8; 40];
        packet[0] = 0x60;
        packet[6] = PROTO_TCP;
        packet[8..24].copy_from_slice(&Ipv6Addr::LOCALHOST.octets());
        packet[24..40].copy_from_slice(&"fc00::5".parse::<Ipv6Addr>().unwrap().octets());
        packet.extend_from_slice(&tcp(1234, 443, TCP_FLAG_SYN));
        let parsed = parse_packet(&packet).expect("parses");
        assert_eq!(parsed.key.destination, "[fc00::5]:443".parse().unwrap());
        assert!(parsed.is_connection_open);
    }

    #[test]
    fn packets_the_relay_does_not_handle_are_rejected() {
        // ICMP.
        assert!(parse_packet(&ipv4(1, &[0u8; 8])).is_none());
        // Truncated transport header.
        assert!(parse_packet(&ipv4(PROTO_TCP, &[0u8; 4])).is_none());
        // Not an IP packet at all.
        assert!(parse_packet(&[0xff, 0x00]).is_none());
        assert!(parse_packet(&[]).is_none());
        // IPv6 with an extension-header chain (hop-by-hop = 0).
        let mut v6 = vec![0u8; 40];
        v6[0] = 0x60;
        v6[6] = 0;
        v6.extend_from_slice(&[0u8; 20]);
        assert!(parse_packet(&v6).is_none());
    }

    #[test]
    fn non_initial_ipv4_fragments_are_ignored() {
        let mut packet = ipv4(PROTO_TCP, &tcp(1, 2, TCP_FLAG_SYN));
        packet[6..8].copy_from_slice(&185u16.to_be_bytes()); // fragment offset
        assert!(parse_packet(&packet).is_none());
    }
}
